In [1]:
import selenium
import time
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time #importing necessary libraries

In [74]:
driver=webdriver.Chrome(r"C:\Webdriver\chromedriver.exe") #loading chrome from C-drive and assigning a variable to it

In [195]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos") # loading website in the chrome driver

In [4]:
driver.maximize_window() #To maximise the window

In [216]:
Video=[] #Making an empty list 
Video_Tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]") #Scraping the data via Xpath
for i in Video_Tag:
    Video.append(i.text.split('\n')[2:])

In [217]:
Video

[['1. "Baby Shark Dance"[3] Pinkfong Baby Shark - Kids\' Songs & Stories 10.95 June 17, 2016 [A]',
  '2. "Despacito"[6] Luis Fonsi 7.90 January 12, 2017 [B]',
  '3. "Johny Johny Yes Papa"[12] LooLoo Kids 6.39 October 8, 2016 [C]',
  '4. "Shape of You"[13] Ed Sheeran 5.76 January 30, 2017 [D]',
  '5. "See You Again"[15] Wiz Khalifa 5.57 April 6, 2015 [E]',
  '6. "Bath Song"[20] Cocomelon – Nursery Rhymes 5.51 May 2, 2018 [F]',
  '7. "Phonics Song with Two Words"[21] ChuChu TV 4.72 March 6, 2014 [G]',
  '8. "Uptown Funk"[22] Mark Ronson 4.63 November 19, 2014 [H]',
  '9. "Learning Colors – Colorful Eggs on a Farm"[23] Miroshka TV 4.59 February 27, 2018 [I]',
  '10. "Masha and the Bear – Recipe for Disaster"[24] Get Movies 4.50 January 31, 2012 [J]',
  '11. "Gangnam Style"[25] Psy 4.48 July 15, 2012 [K]',
  '12. "Wheels on the Bus"[30] Cocomelon – Nursery Rhymes 4.20 May 24, 2018',
  '13. "Dame Tu Cosita"[31] El Chombo 3.98 April 5, 2018',
  '14. "Sugar"[32] Maroon 5 3.72 January 14, 2015',
  '15. "Roar"[33] Katy Perry 3.61 September 5, 2013',
  '16. "Counting Stars"[34] OneRepublic 3.61 May 31, 2013',
  '17. "Sorry"[35] Justin Bieber 3.56 October 22, 2015',
  '18. "Thinking Out Loud"[36] Ed Sheeran 3.47 October 7, 2014',
  '19. "Axel F"[37] Crazy Frog 3.42 June 16, 2009',
  '20. "Girls Like You"[38] Maroon 5 3.31 May 31, 2018',
  '21. "Faded"[39] Alan Walker 3.31 December 3, 2015',
  '22. "Dark Horse"[40] Katy Perry 3.30 February 20, 2014',
  '23. "Baa Baa Black Sheep"[41] Cocomelon – Nursery Rhymes 3.29 June 25, 2018',
  '24. "Let Her Go"[42] Passenger 3.26 July 25, 2012',
  '25. "Bailando"[43] Enrique Iglesias 3.23 April 11, 2014',
  '26. "Lean On"[44] Major Lazer 3.23 March 22, 2015',
  '27. "Perfect"[45] Ed Sheeran 3.20 November 9, 2017',
  '28. "Waka Waka (This Time for Africa)"[46] Shakira 3.19 June 4, 2010',
  '29. "Shake It Off"[47] Taylor Swift 3.19 August 18, 2014',
  '30. "Mi Gente"[48] J Balvin 3.10 June 29, 2017',
  'As of July 14, 2022']]

# 1st ODI

In [63]:
driver.get("https://www.bcci.tv/") # loading website in the chrome driver

In [65]:
driver.maximize_window() #maximising the tab

In [66]:
Tab=driver.find_element_by_xpath("/html/body/nav/div[1]/button/span[1]")
Tab.click() #Clicking on the tab

In [67]:
International=driver.find_element_by_xpath("/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
International.click() #Clicking on the international tab

In [68]:
#Scraping the match title
Match_tag=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div[3]/div/div[4]/div/span[1]")
Match_Title=Match_tag.text
Match_Title

'1st ODI -'

In [69]:
Match_Titles=pd.Series(Match_Title) #Making Series

In [70]:
#Scraping the series
Series_tag=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div[3]/div/div[1]/h5[2]/span")
Series_Title=Series_tag.text
Series_Title

'INDIA TOUR OF WEST INDIES ODI SERIES 2022'

In [71]:
Series_Titles=pd.Series(Series_Title) #making series

In [72]:
#Scraping the place
Place_tag=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div[3]/div/div[4]/div")
Place_Title=Place_tag.text.split('-')[1]
Place_Title

' Queens Park Oval, Trinidad'

In [73]:
Place_Titles=pd.Series(Place_Title)

In [36]:
#Scraping the date
Date_tag=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div[3]/div/div[1]/div/div[1]/h5")
Date_Title=Date_tag.text
Date_Title

'22 JUL 2022'

In [37]:
Dates=pd.Series(Date_Title) #Making a series

In [38]:
#Scraping the time
Time_tag=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div[3]/div/div[1]/div/div[2]/h5")
Time_Title=Time_tag.text
Time_Title

'7:00 PM IST'

In [74]:
Time_Titles=pd.Series(Time_Title)

In [80]:
First_ODI=pd.concat([Match_Titles,Series_Titles,Place_Titles,Dates,Time_Titles],axis=1)
First_ODI.columns=['Match_Title','Series','Place','Date','Time']
First_ODI #Making a dataframe

,Match_Title,Series,Place,Date,Time
0,1st ODI -,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval, Trinidad",22 JUL 2022,7:00 PM IST

# Selenium Exception

In [222]:
driver.get("https://www.guru99.com/") # loading website in the chrome driver

In [223]:
Selenium=driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a")
Selenium.click() #Clicking on Selenium

In [224]:
for i in range(0,10):
    driver.execute_script("window.scrollBy(0,500)")

In [91]:
#Scrolling down to get the Exception Handling

In [226]:
Exception=driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a")
Exception.click() #Clicking on the exception tutorial
time.sleep(10)

In [227]:
for i in range(0,2):
    driver.execute_script("window.scrollBy(0,200)") #Scrolling down to get the exception list

In [231]:
List=[]
Exception_Tag=driver.find_elements_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div/table")
for i in Exception_Tag:
    List.append(i.text.splitlines()[1:])
List

[['ElementNotVisibleException This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
  'ElementNotSelectableException This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
  'NoSuchElementException This Exception occurs if an element could not be found.',
  'NoSuchFrameException This Exception occurs if the frame target to be switched to does not exist.',
  'NoAlertPresentException This Exception occurs when you switch to no presented alert.',
  'NoSuchWindowException This Exception occurs if the window target to be switch does not exist.',
  'StaleElementReferenceException This Selenium exception occurs happens when the web element is detached from the current DOM.',
  'SessionNotFoundException The WebDriver is acting after you quit the browser.',
  'TimeoutException Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.',
  'WebDriverException This Exception takes place when the WebDriver is acting right after you close the browser.',
  'ConnectionClosedException This type of Exception takes place when there is a disconnection in the driver.',
  'ElementClickInterceptedException The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
  'ElementNotInteractableException This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
  'ErrorInResponseException This happens while interacting with the Firefox extension or the remote driver server.',
  'ErrorHandler.UnknownServerException Exception is used as a placeholder in case if the server returns an error without a stack trace.',
  'ImeActivationFailedException This expectation will occur when IME engine activation has failed.',
  'ImeNotAvailableException It takes place when IME support is unavailable.',
  'InsecureCertificateException Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
  'InvalidArgumentException It occurs when an argument does not belong to the expected type.',
  'InvalidCookieDomainException This happens when you try to add a cookie under a different domain instead of current URL.',
  'InvalidCoordinatesException This type of Exception matches an interacting operation that is not valid.',
  'InvalidElementStateExceptio It occurs when command can’t be finished when the element is invalid.',
  'InvalidSessionIdException This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
  'InvalidSwitchToTargetException This occurs when the frame or window target to be switched does not exist.',
  'JavascriptException This issue occurs while executing JavaScript given by the user.',
  'JsonException It occurs when you afford to get the session when the session is not created.',
  'NoSuchAttributeException This kind of Exception occurs when the attribute of an element could not be found.',
  'MoveTargetOutOfBoundsException It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
  'NoSuchContextException ContextAware does mobile device testing.',
  'NoSuchCookieException This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
  'NotFoundException This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
  'RemoteDriverServerException This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
  'ScreenshotException It is not possible to capture a screen.',
  'SessionNotCreatedException It happens when a new session could not be successfully created.',
  'UnableToSetCookieException This occurs if a driver is unable to set a cookie.',
  'UnexpectedTagNameException Happens if a support class did not get a web element as expected.',
  'UnhandledAlertException This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
  'UnexpectedAlertPresentException It occurs when there is the appearance of an unexpected alert.',
  'UnknownMethodException This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
  'UnreachableBrowserException This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
  'UnsupportedCommandException This occurs when remote WebDriver does n’t send valid commands as expected.']]

# State wise GDP

In [99]:
driver=webdriver.Chrome(r"C:\Webdriver 1\chromedriver.exe") #loading chrome from C-drive and assigning a variable to it

In [100]:
driver.get(" http://statisticstimes.com/") # loading website in the chrome driver

In [101]:
driver.maximize_window() #To maximise the window

In [102]:
Economy=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button")
Economy.click() #Clicking on the economy button

In [103]:
India=driver.find_element_by_xpath("//div[@class='dropdown-content']/a[3]")
driver.get(India.get_attribute('href'))

In [104]:
GDP=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
GDP.click() #Clicking on GDP of Indian State

In [105]:
for i in range(0,5):
    driver.execute_script("window.scrollBy(0,500)") #Scrolling down

In [106]:
Rank=[]
Rank_Tag=driver.find_elements_by_xpath("//td[@class='data1']")
for i in Rank_Tag:
    Rank.append(i.text)
    
Rank #Scraping the rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '']

In [107]:
Ranks=Rank[0:33]
Ranks

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [108]:
Ranks=pd.DataFrame(Rank)

In [109]:
State=[]
State_Tag=driver.find_elements_by_xpath("//td[@class='name']")
for i in State_Tag:
    State.append(i.text)
    
State #Scraping the rank

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands',
 'India',
 'Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Karnataka',
 'Gujarat',
 'West Bengal',
 'Rajasthan',
 'Telangana',
 'Andhra Pradesh',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Jharkhand',
 'Chhattisgarh',
 'Uttarakhand',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Manipur',
 'Sikkim',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands',
 'India']

In [110]:
States=State[0:33]
States

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [111]:
State_New=pd.DataFrame(States)

In [112]:
GSDP_1=[]
GSDP_Tag=driver.find_elements_by_xpath("//td[@class='data']")
for i in GSDP_Tag:
    GSDP_1.append(i.text)
    
GSDP_1 #Scraping the GSDP for the year 19-20

['-',
 '13.94%',
 '399.921',
 '-',
 '2,039,074',
 '1,845,853',
 '8.63%',
 '247.629',
 '1,312,929',
 '1,215,307',
 '1,687,818',
 '8.39%',
 '240.726',
 '1,166,817',
 '1,123,982',
 '-',
 '7.96%',
 '228.290',
 '-',
 '1,186,379',
 '1,631,977',
 '7.91%',
 '226.806',
 '1,156,039',
 '1,091,077',
 '1,253,832',
 '5.77%',
 '165.556',
 '793,223',
 '739,525',
 '1,020,989',
 '4.99%',
 '143.179',
 '711,627',
 '677,428',
 '972,782',
 '4.57%',
 '131.083',
 '672,018',
 '621,301',
 '969,604',
 '4.56%',
 '130.791',
 '663,258',
 '612,828',
 '906,672',
 '4.29%',
 '122.977',
 '561,801',
 '522,009',
 '-',
 '4.14%',
 '118.733',
 '-',
 '559,412',
 '856,112',
 '4.10%',
 '117.703',
 '634,408',
 '590,569',
 '831,610',
 '3.89%',
 '111.519',
 '572,240',
 '531,085',
 '611,804',
 '2.81%',
 '80.562',
 '414,977',
 '375,651',
 '574,760',
 '2.79%',
 '79.957',
 '418,868',
 '397,669',
 '521,275',
 '2.58%',
 '74.098',
 '396,499',
 '376,877',
 '-',
 '1.67%',
 '47.982',
 '-',
 '234,048',
 '329,180',
 '1.61%',
 '46.187',
 '243,477',
 '231,182',
 '328,598',
 '1.57%',
 '45.145',
 '240,036',
 '224,986',
 '-',
 '1.30%',
 '37.351',
 '-',
 '193,273',
 '-',
 '0.83%',
 '23.690',
 '-',
 '112,755',
 '165,472',
 '0.81%',
 '23.369',
 '124,403',
 '117,851',
 '80,449',
 '0.39%',
 '11.115',
 '63,408',
 '57,787',
 '55,984',
 '0.26%',
 '7.571',
 '40,583',
 '36,963',
 '-',
 '0.22%',
 '6.397',
 '-',
 '31,192',
 '38,253',
 '0.18%',
 '5.230',
 '25,093',
 '23,013',
 '36,572',
 '0.18%',
 '5.086',
 '26,695',
 '24,682',
 '32,496',
 '0.15%',
 '4.363',
 '20,017',
 '18,722',
 '31,790',
 '0.15%',
 '4.233',
 '20,673',
 '19,300',
 '-',
 '0.14%',
 '4.144',
 '-',
 '17,647',
 '-',
 '0.13%',
 '3.737',
 '-',
 '16,676',
 '26,503',
 '0.12%',
 '3.385',
 '18,797',
 '16,478',
 '-',
 '-',
 '-',
 '-',
 '-',
 '20,351,013',
 '18,886,957',
 '',
 '2,869',
 '14,569,268',
 '14,003,316',
 '-',
 '13.97%',
 '-',
 '1,794,123',
 '1,659,210',
 '8.77%',
 '1,167,776',
 '1,079,894',
 '1,495,758',
 '8.41%',
 '1,015,735',
 '979,159',
 '1,476,983',
 '8.09%',
 '1,035,131',
 '976,948',
 '-',
 '7.92%',
 '-',
 '1,036,859',
 '1,150,711',
 '5.96%',
 '713,376',
 '662,432',
 '916,014',
 '5.06%',
 '630,693',
 '600,433',
 '881,873',
 '4.68%',
 '594,806',
 '549,481',
 '875,429',
 '4.65%',
 '595,605',
 '550,584',
 '827,019',
 '4.41%',
 '496,798',
 '461,903',
 '-',
 '4.24%',
 '-',
 '513,322',
 '779,647',
 '4.22%',
 '568,265',
 '529,739',
 '755,790',
 '3.99%',
 '514,983',
 '477,834',
 '562,710',
 '2.91%',
 '377,276',
 '340,512',
 '517,521',
 '2.83%',
 '374,015',
 '354,830',
 '457,757',
 '2.56%',
 '344,437',
 '327,805',
 '-',
 '1.69%',
 '-',
 '207,193',
 '301,242',
 '1.63%',
 '218,232',
 '204,423',
 '288,041',
 '1.60%',
 '210,837',
 '200,453',
 '-',
 '1.33%',
 '-',
 '173,211',
 '143,063',
 '0.80%',
 '107,171',
 '101,534',
 '-',
 '0.78%',
 '-',
 '91,666',
 '72,181',
 '0.40%',
 '56,810',
 '51,878',
 '50,227',
 '0.27%',
 '35,980',
 '32,830',
 '-',
 '0.22%',
 '-',
 '27,565',
 '34,823',
 '0.19%',
 '22,291',
 '20,534',
 '32,833',
 '0.18%',
 '23,564',
 '21,779',
 '29,148',
 '0.15%',
 '18,549',
 '17,228',
 '28,391',
 '0.15%',
 '17,060',
 '15,972',
 '-',
 '0.15%',
 '-',
 '15,381',
 '-',
 '0.13%',
 '-',
 '15,013',
 '24,424',
 '0.13%',
 '17,797',
 '15,372',
 '-',
 '-',
 '-',
 '-',
 '17,994,301',
 '16,704,645',
 '',
 '12,681,246',
 '12,240,380']

In [113]:
GSDP_2=GSDP_1[0:309:5]
GSDP_3=GSDP_2[0:33]
GSDP_3 #Slicing the data

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [114]:
GSDP5=pd.DataFrame(GSDP_3)

In [115]:
GSDP2=[]
GSDP_Tag=driver.find_elements_by_xpath("//td[@class='data sorting_1']")
for i in GSDP_Tag:
    GSDP2.append(i.text)
    
GSDP2 #Scraping the GSDP for 19-20

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-',
 '2,332,992',
 '1,465,361',
 '1,404,761',
 '1,351,553',
 '1,322,936',
 '995,502',
 '845,247',
 '782,370',
 '776,140',
 '737,156',
 '707,542',
 '704,529',
 '666,075',
 '486,776',
 '472,506',
 '428,031',
 '282,782',
 '271,990',
 '266,537',
 '221,871',
 '133,303',
 '129,877',
 '66,060',
 '44,835',
 '37,571',
 '31,415',
 '29,544',
 '25,323',
 '25,141',
 '24,534',
 '22,488',
 '20,947',
 '-']

In [116]:
GSDP4=GSDP2[0:33]
GSDP4

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-']

In [117]:
GSDP6=pd.DataFrame(GSDP4)

In [118]:
Share=[]
Share_Tag=driver.find_elements_by_xpath("//td[@class='data']")
for i in Share_Tag:
    Share.append(i.text)
    
Share #Scraping the rank

['-',
 '13.94%',
 '399.921',
 '-',
 '2,039,074',
 '1,845,853',
 '8.63%',
 '247.629',
 '1,312,929',
 '1,215,307',
 '1,687,818',
 '8.39%',
 '240.726',
 '1,166,817',
 '1,123,982',
 '-',
 '7.96%',
 '228.290',
 '-',
 '1,186,379',
 '1,631,977',
 '7.91%',
 '226.806',
 '1,156,039',
 '1,091,077',
 '1,253,832',
 '5.77%',
 '165.556',
 '793,223',
 '739,525',
 '1,020,989',
 '4.99%',
 '143.179',
 '711,627',
 '677,428',
 '972,782',
 '4.57%',
 '131.083',
 '672,018',
 '621,301',
 '969,604',
 '4.56%',
 '130.791',
 '663,258',
 '612,828',
 '906,672',
 '4.29%',
 '122.977',
 '561,801',
 '522,009',
 '-',
 '4.14%',
 '118.733',
 '-',
 '559,412',
 '856,112',
 '4.10%',
 '117.703',
 '634,408',
 '590,569',
 '831,610',
 '3.89%',
 '111.519',
 '572,240',
 '531,085',
 '611,804',
 '2.81%',
 '80.562',
 '414,977',
 '375,651',
 '574,760',
 '2.79%',
 '79.957',
 '418,868',
 '397,669',
 '521,275',
 '2.58%',
 '74.098',
 '396,499',
 '376,877',
 '-',
 '1.67%',
 '47.982',
 '-',
 '234,048',
 '329,180',
 '1.61%',
 '46.187',
 '243,477',
 '231,182',
 '328,598',
 '1.57%',
 '45.145',
 '240,036',
 '224,986',
 '-',
 '1.30%',
 '37.351',
 '-',
 '193,273',
 '-',
 '0.83%',
 '23.690',
 '-',
 '112,755',
 '165,472',
 '0.81%',
 '23.369',
 '124,403',
 '117,851',
 '80,449',
 '0.39%',
 '11.115',
 '63,408',
 '57,787',
 '55,984',
 '0.26%',
 '7.571',
 '40,583',
 '36,963',
 '-',
 '0.22%',
 '6.397',
 '-',
 '31,192',
 '38,253',
 '0.18%',
 '5.230',
 '25,093',
 '23,013',
 '36,572',
 '0.18%',
 '5.086',
 '26,695',
 '24,682',
 '32,496',
 '0.15%',
 '4.363',
 '20,017',
 '18,722',
 '31,790',
 '0.15%',
 '4.233',
 '20,673',
 '19,300',
 '-',
 '0.14%',
 '4.144',
 '-',
 '17,647',
 '-',
 '0.13%',
 '3.737',
 '-',
 '16,676',
 '26,503',
 '0.12%',
 '3.385',
 '18,797',
 '16,478',
 '-',
 '-',
 '-',
 '-',
 '-',
 '20,351,013',
 '18,886,957',
 '',
 '2,869',
 '14,569,268',
 '14,003,316',
 '-',
 '13.97%',
 '-',
 '1,794,123',
 '1,659,210',
 '8.77%',
 '1,167,776',
 '1,079,894',
 '1,495,758',
 '8.41%',
 '1,015,735',
 '979,159',
 '1,476,983',
 '8.09%',
 '1,035,131',
 '976,948',
 '-',
 '7.92%',
 '-',
 '1,036,859',
 '1,150,711',
 '5.96%',
 '713,376',
 '662,432',
 '916,014',
 '5.06%',
 '630,693',
 '600,433',
 '881,873',
 '4.68%',
 '594,806',
 '549,481',
 '875,429',
 '4.65%',
 '595,605',
 '550,584',
 '827,019',
 '4.41%',
 '496,798',
 '461,903',
 '-',
 '4.24%',
 '-',
 '513,322',
 '779,647',
 '4.22%',
 '568,265',
 '529,739',
 '755,790',
 '3.99%',
 '514,983',
 '477,834',
 '562,710',
 '2.91%',
 '377,276',
 '340,512',
 '517,521',
 '2.83%',
 '374,015',
 '354,830',
 '457,757',
 '2.56%',
 '344,437',
 '327,805',
 '-',
 '1.69%',
 '-',
 '207,193',
 '301,242',
 '1.63%',
 '218,232',
 '204,423',
 '288,041',
 '1.60%',
 '210,837',
 '200,453',
 '-',
 '1.33%',
 '-',
 '173,211',
 '143,063',
 '0.80%',
 '107,171',
 '101,534',
 '-',
 '0.78%',
 '-',
 '91,666',
 '72,181',
 '0.40%',
 '56,810',
 '51,878',
 '50,227',
 '0.27%',
 '35,980',
 '32,830',
 '-',
 '0.22%',
 '-',
 '27,565',
 '34,823',
 '0.19%',
 '22,291',
 '20,534',
 '32,833',
 '0.18%',
 '23,564',
 '21,779',
 '29,148',
 '0.15%',
 '18,549',
 '17,228',
 '28,391',
 '0.15%',
 '17,060',
 '15,972',
 '-',
 '0.15%',
 '-',
 '15,381',
 '-',
 '0.13%',
 '-',
 '15,013',
 '24,424',
 '0.13%',
 '17,797',
 '15,372',
 '-',
 '-',
 '-',
 '-',
 '17,994,301',
 '16,704,645',
 '',
 '12,681,246',
 '12,240,380']

In [119]:
Share1=Share[1:309:5]
Share2=Share1[0:33]
Share2 #Slicing the data

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-']

In [123]:
Shares=pd.DataFrame(Share2)

In [125]:
GDP=[]
GDP_Tag=driver.find_elements_by_xpath("//td[@class='data']")
for i in GDP_Tag:
    GDP.append(i.text)
    
GDP #Scraping the rank

['-',
 '13.94%',
 '399.921',
 '-',
 '2,039,074',
 '1,845,853',
 '8.63%',
 '247.629',
 '1,312,929',
 '1,215,307',
 '1,687,818',
 '8.39%',
 '240.726',
 '1,166,817',
 '1,123,982',
 '-',
 '7.96%',
 '228.290',
 '-',
 '1,186,379',
 '1,631,977',
 '7.91%',
 '226.806',
 '1,156,039',
 '1,091,077',
 '1,253,832',
 '5.77%',
 '165.556',
 '793,223',
 '739,525',
 '1,020,989',
 '4.99%',
 '143.179',
 '711,627',
 '677,428',
 '972,782',
 '4.57%',
 '131.083',
 '672,018',
 '621,301',
 '969,604',
 '4.56%',
 '130.791',
 '663,258',
 '612,828',
 '906,672',
 '4.29%',
 '122.977',
 '561,801',
 '522,009',
 '-',
 '4.14%',
 '118.733',
 '-',
 '559,412',
 '856,112',
 '4.10%',
 '117.703',
 '634,408',
 '590,569',
 '831,610',
 '3.89%',
 '111.519',
 '572,240',
 '531,085',
 '611,804',
 '2.81%',
 '80.562',
 '414,977',
 '375,651',
 '574,760',
 '2.79%',
 '79.957',
 '418,868',
 '397,669',
 '521,275',
 '2.58%',
 '74.098',
 '396,499',
 '376,877',
 '-',
 '1.67%',
 '47.982',
 '-',
 '234,048',
 '329,180',
 '1.61%',
 '46.187',
 '243,477',
 '231,182',
 '328,598',
 '1.57%',
 '45.145',
 '240,036',
 '224,986',
 '-',
 '1.30%',
 '37.351',
 '-',
 '193,273',
 '-',
 '0.83%',
 '23.690',
 '-',
 '112,755',
 '165,472',
 '0.81%',
 '23.369',
 '124,403',
 '117,851',
 '80,449',
 '0.39%',
 '11.115',
 '63,408',
 '57,787',
 '55,984',
 '0.26%',
 '7.571',
 '40,583',
 '36,963',
 '-',
 '0.22%',
 '6.397',
 '-',
 '31,192',
 '38,253',
 '0.18%',
 '5.230',
 '25,093',
 '23,013',
 '36,572',
 '0.18%',
 '5.086',
 '26,695',
 '24,682',
 '32,496',
 '0.15%',
 '4.363',
 '20,017',
 '18,722',
 '31,790',
 '0.15%',
 '4.233',
 '20,673',
 '19,300',
 '-',
 '0.14%',
 '4.144',
 '-',
 '17,647',
 '-',
 '0.13%',
 '3.737',
 '-',
 '16,676',
 '26,503',
 '0.12%',
 '3.385',
 '18,797',
 '16,478',
 '-',
 '-',
 '-',
 '-',
 '-',
 '20,351,013',
 '18,886,957',
 '',
 '2,869',
 '14,569,268',
 '14,003,316',
 '-',
 '13.97%',
 '-',
 '1,794,123',
 '1,659,210',
 '8.77%',
 '1,167,776',
 '1,079,894',
 '1,495,758',
 '8.41%',
 '1,015,735',
 '979,159',
 '1,476,983',
 '8.09%',
 '1,035,131',
 '976,948',
 '-',
 '7.92%',
 '-',
 '1,036,859',
 '1,150,711',
 '5.96%',
 '713,376',
 '662,432',
 '916,014',
 '5.06%',
 '630,693',
 '600,433',
 '881,873',
 '4.68%',
 '594,806',
 '549,481',
 '875,429',
 '4.65%',
 '595,605',
 '550,584',
 '827,019',
 '4.41%',
 '496,798',
 '461,903',
 '-',
 '4.24%',
 '-',
 '513,322',
 '779,647',
 '4.22%',
 '568,265',
 '529,739',
 '755,790',
 '3.99%',
 '514,983',
 '477,834',
 '562,710',
 '2.91%',
 '377,276',
 '340,512',
 '517,521',
 '2.83%',
 '374,015',
 '354,830',
 '457,757',
 '2.56%',
 '344,437',
 '327,805',
 '-',
 '1.69%',
 '-',
 '207,193',
 '301,242',
 '1.63%',
 '218,232',
 '204,423',
 '288,041',
 '1.60%',
 '210,837',
 '200,453',
 '-',
 '1.33%',
 '-',
 '173,211',
 '143,063',
 '0.80%',
 '107,171',
 '101,534',
 '-',
 '0.78%',
 '-',
 '91,666',
 '72,181',
 '0.40%',
 '56,810',
 '51,878',
 '50,227',
 '0.27%',
 '35,980',
 '32,830',
 '-',
 '0.22%',
 '-',
 '27,565',
 '34,823',
 '0.19%',
 '22,291',
 '20,534',
 '32,833',
 '0.18%',
 '23,564',
 '21,779',
 '29,148',
 '0.15%',
 '18,549',
 '17,228',
 '28,391',
 '0.15%',
 '17,060',
 '15,972',
 '-',
 '0.15%',
 '-',
 '15,381',
 '-',
 '0.13%',
 '-',
 '15,013',
 '24,424',
 '0.13%',
 '17,797',
 '15,372',
 '-',
 '-',
 '-',
 '-',
 '17,994,301',
 '16,704,645',
 '',
 '12,681,246',
 '12,240,380']

In [126]:
GDP1=GDP[2:309:5]
GDP2=GDP1[0:33]
GDP2 #Slicing the data

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-']

In [127]:
GDP_New=pd.DataFrame(GDP2)

In [133]:
State_GDP=pd.concat([Ranks,State_New,GSDP5,GSDP6,Shares,GDP_New],axis=1,ignore_index=True)
State_GDP.columns=['Rank','State','19-20','18-19','Share','GDP']
State_GDP.head(33)

   Rank                      State      19-20      18-19   Share      GDP
0     1                Maharashtra          -  2,632,792  13.94%  399.921
1     2                 Tamil Nadu  1,845,853  1,630,208   8.63%  247.629
2     3              Uttar Pradesh  1,687,818  1,584,764   8.39%  240.726
3     4                    Gujarat          -  1,502,899   7.96%  228.290
4     5                  Karnataka  1,631,977  1,493,127   7.91%  226.806
5     6                West Bengal  1,253,832  1,089,898   5.77%  165.556
6     7                  Rajasthan  1,020,989    942,586   4.99%  143.179
7     8             Andhra Pradesh    972,782    862,957   4.57%  131.083
8     9                  Telangana    969,604    861,031   4.56%  130.791
9    10             Madhya Pradesh    906,672    809,592   4.29%  122.977
10   11                     Kerala          -    781,653   4.14%  118.733
11   12                      Delhi    856,112    774,870   4.10%  117.703
12   13                    Haryana    831,610    734,163   3.89%  111.519
13   14                      Bihar    611,804    530,363   2.81%   80.562
14   15                     Punjab    574,760    526,376   2.79%   79.957
15   16                     Odisha    521,275    487,805   2.58%   74.098
16   17                      Assam          -    315,881   1.67%   47.982
17   18               Chhattisgarh    329,180    304,063   1.61%   46.187
18   19                  Jharkhand    328,598    297,204   1.57%   45.145
19   20                Uttarakhand          -    245,895   1.30%   37.351
20   21            Jammu & Kashmir          -    155,956   0.83%   23.690
21   22           Himachal Pradesh    165,472    153,845   0.81%   23.369
22   23                        Goa     80,449     73,170   0.39%   11.115
23   24                    Tripura     55,984     49,845   0.26%    7.571
24   25                 Chandigarh          -     42,114   0.22%    6.397
25   26                 Puducherry     38,253     34,433   0.18%    5.230
26   27                  Meghalaya     36,572     33,481   0.18%    5.086
27   28                     Sikkim     32,496     28,723   0.15%    4.363
28   29                    Manipur     31,790     27,870   0.15%    4.233
29   30                   Nagaland          -     27,283   0.14%    4.144
30   31          Arunachal Pradesh          -     24,603   0.13%    3.737
31   32                    Mizoram     26,503     22,287   0.12%    3.385
32   33  Andaman & Nicobar Islands          -          -       -        -

# Github

In [234]:
driver.get("https://github.com/") # loading website in the chrome driver

In [235]:
Drop_down=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[1]/div[2]/button")
Drop_down.click()

In [236]:
Explore=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]")
Explore.click() #Clicking on explore

In [237]:
Trending=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
Trending.click() #Clicking on trending button

In [238]:
Repository=[]
Repository_Tag=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
for i in Repository_Tag:
    Repository.append(i.text)
    
Repository #Scraping repository name

['rust-lang / rustlings',
 'logto-io / logto',
 'codecrafters-io / build-your-own-x',
 'srush / GPU-Puzzles',
 'ytdl-org / youtube-dl',
 'jart / cosmopolitan',
 'TheAlgorithms / JavaScript',
 'trpc / trpc',
 'dair-ai / ML-YouTube-Courses',
 'fossabot / typoraCracker',
 'shengcaishizhan / kkndme_tianya',
 'bambulab / BambuStudio',
 'Moataz-Elmesmary / Data-Science-Roadmap',
 'freqtrade / freqtrade',
 'Anduin2017 / HowToCook',
 'nim-lang / Nim',
 'adiwajshing / Baileys',
 'enaqx / awesome-react',
 'fatedier / frp',
 'wailsapp / wails',
 'github / docs',
 'Hunlongyu / ZY-Player',
 'Asabeneh / 30-Days-Of-React',
 'smartcontractkit / full-blockchain-solidity-course-js',
 'mgunyho / tere']

In [239]:
Repositories=pd.DataFrame(Repository)

In [240]:
Description=[]
Description_Tag=driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']")
for i in Description_Tag:
    Description.append(i.text)
    
Description #Scraping repository description

['🦀 Small exercises to get you used to reading and writing Rust code!',
 '🧑\u200d🚀 Logto helps you build the sign-in, auth, and user identity within minutes. We provide an OIDC-based identity service and the end-user experience with username, phone number, email, and social sign-in, with extendable multi-language support.',
 'Master programming by recreating your favorite technologies from scratch.',
 'Solve puzzles. Learn CUDA.',
 'Command-line program to download videos from YouTube.com and other video sites',
 'build-once run-anywhere c library',
 'Algorithms and Data Structures implemented in JavaScript for beginners, following best practices.',
 '🧙\u200d♀️ Move Fast and Break Nothing. End-to-end typesafe APIs made easy.',
 '📺 A place to discover the latest machine learning courses on YouTube.',
 'A patch and keygen tools for typora.',
 '天涯 kkndme 神贴聊房价',
 "PC Software for BambuLab's 3D printers",
 'Data Science Roadmap from A to Z',
 'Free, open source crypto trading bot',
 "程序员在家做饭方法指南。Programmer's guide about how to cook at home (Chinese only).",
 'Nim is a statically typed compiled systems programming language. It combines successful concepts from mature languages like Python, Ada and Modula. Its design focuses on efficiency, expressiveness, and elegance (in that order of priority).',
 'Lightweight full-featured WhatsApp Web + Multi-Device API',
 'A collection of awesome things regarding React ecosystem',
 'A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.',
 'Create beautiful applications using Go',
 'The open-source repo for docs.github.com',
 '▶️ 跨平台桌面端视频资源播放器.简洁无广告.免费高颜值. 🎞',
 '30 Days of React challenge is a step by step guide to learn React in 30 days. It requires HTML, CSS, and JavaScript knowledge. You should be comfortable with JavaScript before you start to React. If you are not comfortable with JavaScript check out 30DaysOfJavaScript. This is a continuation of 30 Days Of JS. This challenge may take more than 100…',
 'Learn Blockchain, Solidity, and Full Stack Web3 Development with Javascript',
 'Terminal file explorer']

In [241]:
Descriptions=pd.DataFrame(Description)

In [252]:
Language=[]
Language_Tag=driver.find_elements_by_xpath("//div[@class='f6 color-fg-muted mt-2']")
for i in Language_Tag:
    Language.append(i.text.split(" ")[0])
    
Language #Scraping repository language

['Rust',
 'TypeScript',
 '152,581',
 'Jupyter',
 'Python',
 'C',
 'JavaScript',
 'TypeScript',
 '7,332',
 'Python',
 '9,719',
 'C++',
 '159',
 'Python',
 'Shell',
 'Nim',
 'JavaScript',
 '49,378',
 'Go',
 'Go',
 'JavaScript',
 'Vue',
 'JavaScript',
 '3,494',
 'Rust']

In [253]:
for i in range(len(Language)):
    if Language[i]== '152,581': #Replacing  language with - which does not have language
        Language[i]='-'
    if Language[i]== '7,332':
        Language[i]='-'
    if Language[i]=='9,719':
        Language[i]='-'
    if Language[i]=='159':
        Language[i]='-'
    if Language[i]=='49,378':
        Language[i]='-'
    if Language[i]=='3,494':
        Language[i]='-'
            
        
Language

['Rust',
 'TypeScript',
 '-',
 'Jupyter',
 'Python',
 'C',
 'JavaScript',
 'TypeScript',
 '-',
 'Python',
 '-',
 'C++',
 '-',
 'Python',
 'Shell',
 'Nim',
 'JavaScript',
 '-',
 'Go',
 'Go',
 'JavaScript',
 'Vue',
 'JavaScript',
 '-',
 'Rust']

In [251]:
Languages=pd.DataFrame(Language)

In [256]:
Contributors=[]
Contributors_Tag=driver.find_elements_by_xpath("//div[@class='f6 color-fg-muted mt-2']")
for i in Contributors_Tag:
    Contributors.append(i.text.split(" ")[2])
    
Contributors #Scraping repository contributors

['4,253',
 '22',
 'Built',
 '1,639',
 '7,950',
 '234',
 '3,662',
 '274',
 'Built',
 '123',
 'Built',
 '9',
 'Built',
 '3,880',
 '6,869',
 '1,331',
 '994',
 'Built',
 '10,426',
 '440',
 '55,706',
 '1,843',
 '3,647',
 'Built',
 '16']

In [257]:
for i in range(len(Contributors)):
    if Contributors[i]== 'Built': #Replacing  contributors with - which does not have any contributor
        Contributors[i]='-'
Contributors

['4,253',
 '22',
 '-',
 '1,639',
 '7,950',
 '234',
 '3,662',
 '274',
 '-',
 '123',
 '-',
 '9',
 '-',
 '3,880',
 '6,869',
 '1,331',
 '994',
 '-',
 '10,426',
 '440',
 '55,706',
 '1,843',
 '3,647',
 '-',
 '16']

In [258]:
Contributor=pd.DataFrame(Contributors)

In [259]:
Github=pd.concat([Repositories,Descriptions,Contributor,Languages],axis=1)
Github.columns=['Repository','Description','Contributor','Language']
Github

,Repository,Description,Contributor,Language
0,rust-lang / rustlings,🦀 Small exercises to get you used to reading a...,"4,253",Rust
1,logto-io / logto,"🧑‍🚀 Logto helps you build the sign-in, auth, a...",22,TypeScript
2,codecrafters-io / build-your-own-x,Master programming by recreating your favorite...,-,-
3,srush / GPU-Puzzles,Solve puzzles. Learn CUDA.,"1,639",Jupyter
4,ytdl-org / youtube-dl,Command-line program to download videos from Y...,"7,950",Python
5,jart / cosmopolitan,build-once run-anywhere c library,234,C
6,TheAlgorithms / JavaScript,Algorithms and Data Structures implemented in ...,"3,662",JavaScript
7,trpc / trpc,🧙‍♀️ Move Fast and Break Nothing. End-to-end t...,274,TypeScript
8,dair-ai / ML-YouTube-Courses,📺 A place to discover the latest machine learn...,-,-
9,fossabot / typoraCracker,A patch and keygen tools for typora.,123,Python
10,shengcaishizhan / kkndme_tianya,天涯 kkndme 神贴聊房价,-,-
11,bambulab / BambuStudio,PC Software for BambuLab's 3D printers,9,C++
12,Moataz-Elmesmary / Data-Science-Roadmap,Data Science Roadmap from A to Z,-,-
13,freqtrade / freqtrade,"Free, open source crypto trading bot","3,880",Python
14,Anduin2017 / HowToCook,程序员在家做饭方法指南。Programmer's guide about how to co...,"6,869",Shell
15,nim-lang / Nim,Nim is a statically typed compiled systems pro...,"1,331",Nim
16,adiwajshing / Baileys,Lightweight full-featured WhatsApp Web + Multi...,994,JavaScript
17,enaqx / awesome-react,A collection of awesome things regarding React...,-,-
18,fatedier / frp,A fast reverse proxy to help you expose a loca...,"10,426",Go
19,wailsapp / wails,Create beautiful applications using Go,440,Go
20,github / docs,The open-source repo for docs.github.com,"55,706",JavaScript
21,Hunlongyu / ZY-Player,▶️ 跨平台桌面端视频资源播放器.简洁无广告.免费高颜值. 🎞,"1,843",Vue
22,Asabeneh / 30-Days-Of-React,30 Days of React challenge is a step by step g...,"3,647",JavaScript
23,smartcontractkit / full-blockchain-solidity-co...,"Learn Blockchain, Solidity, and Full Stack Web...",-,-
24,mgunyho / tere,Terminal file explorer,16,Rust

# Bill Boards

In [4]:
driver=webdriver.Chrome(r"C:\Webdriver\chromedriver.exe") #loading chrome from C-drive and assigning a variable to it

In [262]:
driver.get("https://www.billboard.com/")

In [6]:
driver.maximize_window() # to maximise window

In [263]:
Menu=driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/div/div[1]/button")
Menu.click() #Clicking on menu

In [266]:
Rank=[]
Rank_Tag=driver.find_elements_by_xpath("//span[@class='c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet']")
for i in Rank_Tag:
    Rank.append(i.text)
    
Rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100']

In [267]:
Ranks=pd.DataFrame(Rank)

In [13]:
Song1=[]
Song1_Tag=driver.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']")
for i in Song1_Tag:
    Song1.append(i.text)
    
Song1

['As It Was']

In [14]:
Song=[]
Song_Tag=driver.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
for i in Song_Tag:
    Song.append(i.text)
    
Song

['About Damn Time',
 'First Class',
 'Running Up That Hill (A Deal With God)',
 'Wait For U',
 'Jimmy Cooks',
 'Me Porto Bonito',
 'Heat Waves',
 'Break My Soul',
 'Big Energy',
 'Titi Me Pregunto',
 'Wasted On You',
 'Hot Shit',
 'Glimpse Of Us',
 'Late Night Talking',
 'Stay',
 'I Like You (A Happier Song)',
 'Numb Little Bug',
 'The Kind Of Love We Make',
 'Sunroof',
 'Get Into It (Yuh)',
 'Ghost',
 'Boyfriend',
 'Sticky',
 'Bad Habits',
 'Moscow Mule',
 'Like I Love Country Music',
 'You Proof',
 'Cold Heart (PNAU Remix)',
 'Enemy',
 'Vegas',
 'Woman',
 'She Had Me At Heads Carolina',
 'Shivers',
 'Super Gremlin',
 'Provenza',
 'Something In The Orange',
 'Damn Strait',
 'Take My Name',
 'Master Of Puppets',
 'Thats What I Want',
 'Efecto',
 'Fall In Love',
 "I Ain't Worried",
 'In A Minute',
 'Sweetest Pie',
 'Left And Right',
 '2step',
 'Thousand Miles',
 'Despues de La Playa',
 'Trouble With A Heartbreak',
 'Party',
 'What Happened To Virgil',
 'Rock And A Hard Place',
 'Sleazy Flow',
 'Massive',
 'Ojitos Lindos',
 'Puffin On Zootiez',
 'Cooped Up',
 "When You're Gone",
 '5 Foot 9',
 'Last Night Lonely',
 'Bam Bam',
 'Tarot',
 'Hold My Hand',
 'Silent Hill',
 'Son Of A Sinner',
 'Flower Shops',
 'So Good',
 'Good Love',
 'Wishful Drinking',
 'Hotel Lobby (Unc And Phew)',
 '7500 OBO',
 'To The Moon!',
 "F.N.F. (Let's Go)",
 'Country On',
 'Whiskey On You',
 'New Truck',
 'Circles Around This Town',
 'Wild As Her',
 'Love Me More',
 'More',
 'Numb',
 'Cash In Cash Out',
 'Un Ratito',
 'Ghost Story',
 'Right On',
 'Thought You Should Know',
 'Te Felicito',
 'She Likes It',
 'Plan B',
 'Desesperados',
 'La Corriente',
 'Bones',
 'Until I Found You',
 'Best Thing Since Backroads',
 'U-Digg',
 'Unstoppable',
 'Rich Minion',
 'Bad Habit']

In [17]:
Songs=Song1+Song #appending both 1st song with the rest

In [49]:
Songs2=pd.DataFrame(Songs)

In [18]:
Artist1=[]
Artist1_Tag=driver.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']")
for i in Artist1_Tag:
    Artist1.append(i.text)
    
Artist1

['Harry Styles']

In [19]:
Artist=[]
Artist_Tag=driver.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
for i in Artist_Tag:
    Artist.append(i.text)
    
Artist

['Lizzo',
 'Jack Harlow',
 'Kate Bush',
 'Future Featuring Drake & Tems',
 'Drake Featuring 21 Savage',
 'Bad Bunny & Chencho Corleone',
 'Glass Animals',
 'Beyonce',
 'Latto',
 'Bad Bunny',
 'Morgan Wallen',
 'Cardi B, Ye & Lil Durk',
 'Joji',
 'Harry Styles',
 'The Kid LAROI & Justin Bieber',
 'Post Malone Featuring Doja Cat',
 'Em Beihold',
 'Luke Combs',
 'Nicky Youre & dazy',
 'Doja Cat',
 'Justin Bieber',
 'Dove Cameron',
 'Drake',
 'Ed Sheeran',
 'Bad Bunny',
 'Kane Brown',
 'Morgan Wallen',
 'Elton John & Dua Lipa',
 'Imagine Dragons X JID',
 'Doja Cat',
 'Doja Cat',
 'Cole Swindell',
 'Ed Sheeran',
 'Kodak Black',
 'Karol G',
 'Zach Bryan',
 'Scotty McCreery',
 'Parmalee',
 'Metallica',
 'Lil Nas X',
 'Bad Bunny',
 'Bailey Zimmerman',
 'OneRepublic',
 'Lil Baby',
 'Megan Thee Stallion & Dua Lipa',
 'Charlie Puth Featuring Jung Kook',
 'Ed Sheeran Featuring Lil Baby',
 'The Kid LAROI',
 'Bad Bunny',
 'Jason Aldean',
 'Bad Bunny & Rauw Alejandro',
 'Lil Durk Featuring Gunna',
 'Bailey Zimmerman',
 'SleazyWorld Go Featuring Lil Baby',
 'Drake',
 'Bad Bunny & Bomba Estereo',
 'Future',
 'Post Malone Featuring Roddy Ricch',
 'Shawn Mendes',
 'Tyler Hubbard',
 'Jon Pardi',
 'Camila Cabello Featuring Ed Sheeran',
 'Bad Bunny & Jhay Cortez',
 'Lady Gaga',
 'Kendrick Lamar & Kodak Black',
 'Jelly Roll',
 'ERNEST Featuring Morgan Wallen',
 'Halsey',
 'City Girls & Usher',
 'Ingrid Andress With Sam Hunt',
 'Quavo & Takeoff',
 'Tim McGraw',
 'JNR CHOI & Sam Tompkins',
 'Hitkidd & Glorilla',
 'Luke Bryan',
 'Nate Smith',
 'Dylan Scott',
 'Maren Morris',
 'Corey Kent',
 'Sam Smith',
 'j-hope',
 'Marshmello & Khalid',
 'Pharrell Williams Featuring 21 Savage & Tyler, The Creator',
 'Bad Bunny',
 'Carrie Underwood',
 'Lil Baby',
 'Morgan Wallen',
 'Shakira & Rauw Alejandro',
 'Russell Dickerson & Jake Scott',
 'Megan Thee Stallion',
 'Rauw Alejandro & Chencho Corleone',
 'Bad Bunny & Tony Dize',
 'Imagine Dragons',
 'Stephen Sanchez',
 'Jake Owen',
 'Lil Baby, 42 Dugg & Veeze',
 'Sia',
 'Yeat',
 'Steve Lacy']

In [20]:
Artists=Artist1+Artist

In [50]:
Artists_1=pd.DataFrame(Artists)

In [26]:
Rank_2=[]
Rank_2_Tag=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']")
for i in Rank_2_Tag:
    Rank_2.append(i.text)
    
Rank_2

['1',
 '14',
 '3',
 '12',
 '2',
 '13',
 '6',
 '26',
 '4',
 '10',
 '5',
 '3',
 '8',
 '9',
 '9',
 '77',
 '7',
 '3',
 '11',
 '37',
 '12',
 '9',
 '14',
 '34',
 '-',
 '1',
 '10',
 '4',
 '18',
 '7',
 '15',
 '52',
 '16',
 '5',
 '19',
 '23',
 '13',
 '3',
 '24',
 '6',
 '23',
 '31',
 '21',
 '41',
 '20',
 '21',
 '17',
 '3',
 '25',
 '54',
 '26',
 '9',
 '31',
 '7',
 '36',
 '8',
 '28',
 '44',
 '27',
 '33',
 '34',
 '5',
 '29',
 '49',
 '38',
 '6',
 '30',
 '43',
 '33',
 '35',
 '32',
 '11',
 '39',
 '11',
 '42',
 '14',
 '35',
 '14',
 '-',
 '1',
 '37',
 '42',
 '40',
 '9',
 '46',
 '10',
 '62',
 '4',
 '51',
 '13',
 '41',
 '17',
 '22',
 '2',
 '50',
 '11',
 '45',
 '11',
 '48',
 '9',
 '43',
 '16',
 '49',
 '9',
 '58',
 '17',
 '61',
 '4',
 '57',
 '6',
 '44',
 '3',
 '53',
 '9',
 '55',
 '10',
 '56',
 '8',
 '59',
 '14',
 '63',
 '4',
 '74',
 '6',
 '47',
 '18',
 '68',
 '9',
 '54',
 '9',
 '65',
 '8',
 '-',
 '1',
 '70',
 '24',
 '86',
 '4',
 '-',
 '1',
 '-',
 '1',
 '73',
 '7',
 '77',
 '6',
 '69',
 '19',
 '88',
 '6',
 '-',
 '1',
 '-',
 '3',
 '87',
 '4',
 '83',
 '24',
 '89',
 '3',
 '85',
 '5',
 '-',
 '1',
 '-',
 '1',
 '81',
 '4',
 '84',
 '9',
 '71',
 '7',
 '90',
 '13',
 '80',
 '9',
 '75',
 '5',
 '93',
 '14',
 '100',
 '6',
 '97',
 '8',
 '-',
 '7',
 '-',
 '8',
 '-',
 '2',
 '-',
 '1',
 '82',
 '3',
 '-',
 '1',
 '-',
 '1',
 '-',
 '1']

In [28]:
Last_Week=Rank_2[0:200:2] #Slicing last week rank

In [51]:
Last_Week1=pd.DataFrame(Last_Week)

In [32]:
Weeks_on_Board=Rank_2[1:200:2] #Slicing Weeks_on_Board

In [52]:
Weeks_on_Board1=pd.DataFrame(Weeks_on_Board)

In [37]:
Peak=[]
Peak_Tag=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max']")
for i in Peak_Tag:
    Peak.append(i.text)
    
Peak

['',
 '1',
 '',
 '2',
 '',
 '1',
 '',
 '4',
 '',
 '1',
 '',
 '1',
 '',
 '7',
 '',
 '1',
 '',
 '7',
 '',
 '3',
 '',
 '5',
 '',
 '9',
 '',
 '13',
 '',
 '8',
 '',
 '4',
 '',
 '1',
 '',
 '9',
 '',
 '18',
 '',
 '13',
 '',
 '20',
 '',
 '21',
 '',
 '5',
 '',
 '16',
 '',
 '6',
 '',
 '2',
 '',
 '4',
 '',
 '27',
 '',
 '6',
 '',
 '7',
 '',
 '5',
 '',
 '31',
 '',
 '7',
 '',
 '33',
 '',
 '4',
 '',
 '3',
 '',
 '25',
 '',
 '37',
 '',
 '38',
 '',
 '22',
 '',
 '40',
 '',
 '8',
 '',
 '34',
 '',
 '43',
 '',
 '44',
 '',
 '14',
 '',
 '15',
 '',
 '22',
 '',
 '48',
 '',
 '15',
 '',
 '6',
 '',
 '32',
 '',
 '14',
 '',
 '22',
 '',
 '24',
 '',
 '47',
 '',
 '14',
 '',
 '26',
 '',
 '4',
 '',
 '12',
 '',
 '38',
 '',
 '61',
 '',
 '62',
 '',
 '21',
 '',
 '18',
 '',
 '49',
 '',
 '7',
 '',
 '67',
 '',
 '64',
 '',
 '55',
 '',
 '70',
 '',
 '71',
 '',
 '59',
 '',
 '73',
 '',
 '38',
 '',
 '75',
 '',
 '76',
 '',
 '77',
 '',
 '78',
 '',
 '52',
 '',
 '80',
 '',
 '81',
 '',
 '82',
 '',
 '83',
 '',
 '26',
 '',
 '16',
 '',
 '61',
 '',
 '13',
 '',
 '12',
 '',
 '67',
 '',
 '63',
 '',
 '29',
 '',
 '91',
 '',
 '32',
 '',
 '87',
 '',
 '95',
 '',
 '96',
 '',
 '52',
 '',
 '98',
 '',
 '99',
 '',
 '100']

In [38]:
Peaks=Peak[1:200:2]
Peaks

['1',
 '2',
 '1',
 '4',
 '1',
 '1',
 '7',
 '1',
 '7',
 '3',
 '5',
 '9',
 '13',
 '8',
 '4',
 '1',
 '9',
 '18',
 '13',
 '20',
 '21',
 '5',
 '16',
 '6',
 '2',
 '4',
 '27',
 '6',
 '7',
 '5',
 '31',
 '7',
 '33',
 '4',
 '3',
 '25',
 '37',
 '38',
 '22',
 '40',
 '8',
 '34',
 '43',
 '44',
 '14',
 '15',
 '22',
 '48',
 '15',
 '6',
 '32',
 '14',
 '22',
 '24',
 '47',
 '14',
 '26',
 '4',
 '12',
 '38',
 '61',
 '62',
 '21',
 '18',
 '49',
 '7',
 '67',
 '64',
 '55',
 '70',
 '71',
 '59',
 '73',
 '38',
 '75',
 '76',
 '77',
 '78',
 '52',
 '80',
 '81',
 '82',
 '83',
 '26',
 '16',
 '61',
 '13',
 '12',
 '67',
 '63',
 '29',
 '91',
 '32',
 '87',
 '95',
 '96',
 '52',
 '98',
 '99',
 '100']

In [53]:
Peaks1=pd.DataFrame(Peak)

In [55]:
BillBoard=pd.concat([Ranks,Songs2,Artists_1,Last_Week1,Peaks1,Weeks_on_Board1],axis=1)
BillBoard.columns=['Rank','Songs','Artist','Last_Week_Position','Peak_Position','Weeks_on_Board']
BillBoard.head(100)

,Rank,Songs,Artist,Last_Week_Position,Peak_Position,Weeks_on_Board
0,1,As It Was,Harry Styles,1,,14
1,2,About Damn Time,Lizzo,3,1,12
2,3,First Class,Jack Harlow,2,,13
3,4,Running Up That Hill (A Deal With God),Kate Bush,6,2,26
4,5,Wait For U,Future Featuring Drake & Tems,4,,10
...,...,...,...,...,...,...
95,96,Best Thing Since Backroads,Jake Owen,-,48,1
96,97,U-Digg,"Lil Baby, 42 Dugg & Veeze",82,,3
97,98,Unstoppable,Sia,-,15,1
98,99,Rich Minion,Yeat,-,,1
99,100,Bad Habit,Steve Lacy,-,6,1

# Data Science

In [75]:
driver.get("https://www.naukri.com/")

In [76]:
search_designation=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[3]/div/div/div[1]/div/div/div/input")
search_designation.send_keys("Data Science") #First giving the designation from home page

In [77]:
search_button=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[3]/div/div/div[6]")
search_button.click() #clicking search button via Xpath location

In [80]:
Recruiter=driver.find_element_by_xpath("//*[@title='Search Recruiters']")
driver.get(Recruiter.get_attribute('href'))

In [81]:
search_designation=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input")
search_designation.send_keys("Data Science") #Giving the designation from recruiter page

In [82]:
search_button=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button")
search_button.click() #clicking search button via Xpath location

In [84]:
Name=[]
Name_Tag=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
for i in Name_Tag:
    Name.append(i.text)
Name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Vaishnavi Kudalkar',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Sakshi Chhikara',
 'Ruchi Dhote',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'Avodha',
 'SREEDHAR',
 'Priya Khare',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury']

In [85]:
Names=pd.DataFrame(Name)

In [86]:
Designation=[]
Designation_Tag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
for i in Designation_Tag:
    Designation.append(i.text)
Designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Executive',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'HR Team Lead',
 'HR Manager',
 'Assistant Manager HR',
 'Senior Executive Talent Acquisition',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Company Recruitment Head',
 'Project Manager',
 'Business Development Associate',
 'Recruitment Consultant',
 'Senior Manager',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner']

In [87]:
Designations=pd.DataFrame(Designation)

In [88]:
Company=[]
Company_Tag=driver.find_elements_by_xpath("//a[@class='ellipsis']")
for i in Company_Tag:
    Company.append(i.text)
Company

['Aakash Harit',
 'Data Science Network',
 'shravan Kumar Gaddam',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'Enerlytics Software Solutions Pvt Ltd',
 'subhas patel',
 'LibraryXProject',
 'Abhishek - Only Analytics Hiring - India and',
 'Apidel Technologies Division of Transpower',
 'Institute for Financial Management and Resear',
 'IFMR',
 'Balu Ramesh',
 'Techvantage Systems Pvt Ltd',
 'Asif Lucknowi',
 'Weupskill- Live Wire India',
 'InstaFinancials',
 'CBL Data Science Private Limited',
 'Vaishnavi Kudalkar',
 'Codeachive learning',
 'Priyanka Akiri',
 'Infinitive Software Solutions',
 'Kalpana Dumpala',
 'Innominds Software',
 'Mubarak',
 'MoneyTap',
 'Kushal Rastogi',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Mahesh Babu Channa',
 'SocialPrachar.com',
 'Kapil Devang',
 'BISP Solutions',
 'Sakshi Chhikara',
 'BIZ INFOTECNO PRIVATE LIMITED',
 'Ruchi Dhote',
 'Bristlecone India Ltd',
 'Manisha Yadav',
 'Easi Tax',
 'Riya Rajesh',
 'Novelworx Digital Solutions',
 'Rashmi Bhattacharjee',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'Faizan Kareem',
 'FirstTech Consaltants Pvt.Ltd',
 'Rithika dadwal',
 'Affine Analytics',
 'Sandhya Khandagale',
 'Compumatrice Multimedia Pvt Ltd',
 'Shaun Rao',
 'Exela Technologies',
 'Azahar Shaikh',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Manas',
 'Autumn Leaf Consulting Services Private...',
 'kumar',
 'trainin',
 'Sunil Vedula',
 'Nanoprecise Sci Corp',
 'Rajat Kumar',
 'R.S Consultancy &amp; Services',
 'Dhruv Dev Dubey',
 'Confidential',
 'Jayanth N',
 'Dollarbird Information Services Pvt, Ltd',
 'Avodha',
 'Nikitha Palaparthi',
 'SREEDHAR',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED',
 'Priya Khare',
 'Independent Consultant',
 'Amit Sharma',
 'ASCO consulting',
 'Kanan',
 'NY INST',
 'Shashikant Chaudhary',
 '3D India Staffing Research &amp; Consulting...',
 'Brad',
 'O.C. Tanner',
 'Rutuja Pawar',
 'Demand Matrix',
 'Madhusudhan Sridhar',
 'MADHUSUDHAN SRIDHAR',
 'Ankit Sinha',
 'Suntech Global',
 'Gaurav Chouhan',
 'Strategic Consulting Lab',
 'Rashi Kacker',
 'Impel Labs Pvt. Ltd.',
 'Ashwini',
 'MRP Advisers',
 'Balaji Kolli',
 'Saras Solutions India Pvt Ltd',
 'Rajani Nagaraj',
 'WildJasmine',
 'ROHIT Kumar',
 'LNT Private Limited',
 'Amir Chowdhury',
 'Granular.ai']

In [89]:
Companies=Company[1:100:2]
Companies #Slicling the company names

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Codeachive learning',
 'Infinitive Software Solutions',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'SocialPrachar.com',
 'BISP Solutions',
 'BIZ INFOTECNO PRIVATE LIMITED',
 'Bristlecone India Ltd',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'Nikitha Palaparthi',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED',
 'Independent Consultant',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai']

In [90]:
Companies1=pd.DataFrame(Companies)

In [91]:
Skill=[]
Skill_Tag=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
for i in Skill_Tag:
    Skill.append(i.text)
Skill

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics, Deep Learning, statistics, Data Analytics, Data Analysis, support vector machine',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Data Science, Python, Data Analytics',
 'Oracle Dba, Data Science, Data Warehousing, ETL, Jupyter, Numpy, Data Transformation, Snowflake, Teradata, Python, Data Manipulation, Relational Databases',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'React.js, Data Science, Java, Front End, Business Analytics, Backend, Tableau, Python, Qa Testing, Automation Testing',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Ethical Hacking, Security Operations Center, SOC, Managed Services, Data Science, Machine Learning, Artificial Intelligence, Operations Research, Education',
 'Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing']

In [92]:
Skills=pd.DataFrame(Skill)

In [101]:
Location=[]
Location_Tag=driver.find_elements_by_xpath("//p[@class='highlightable']")
for i in Location_Tag:
    Location.append(i.text.split('\n')[-1])
Location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Chandigarh',
 'Pune',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Nanoprecise Sci Corp',
 'Delhi',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Granular.ai']

In [104]:
for i in range(len(Location)):
    if Location[i]== 'Nanoprecise Sci Corp': #Replacing the companies with - which does not have location
        Location[i]='-'
    if Location[i]== 'Granular.ai':
        Location[i]='-'
        
Location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Chandigarh',
 'Pune',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 '-',
 'Delhi',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 '-']

In [105]:
Locations=pd.DataFrame(Location)

In [106]:
Recruiter_Detail=pd.concat([Names,Designations,Companies1,Skills,Locations],axis=1)
Recruiter_Detail.columns=['Name','Designation','Company','Skill','Location']
Recruiter_Detail

,Name,Designation,Company,Skill,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",-
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
34,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",-

# Novels

In [107]:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [112]:
for i in range(0,4):
    driver.execute_script("window.scrollBy(0,500)") #Scrolling down

In [113]:
Genre=[]
Genre_Tag=driver.find_elements_by_xpath("//td[@class='last left']")
for i in Genre_Tag:
    Genre.append(i.text)
Genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [114]:
Genres=pd.DataFrame(Genre)

In [115]:
Table=[]
Table_Tag=driver.find_elements_by_xpath("//td[@class='left']")
for i in Table_Tag:
    Table.append(i.text)
Table

['1',
 'Da Vinci Code,The',
 'Brown, Dan',
 '5,094,805',
 'Transworld',
 '2',
 'Harry Potter and the Deathly Hallows',
 'Rowling, J.K.',
 '4,475,152',
 'Bloomsbury',
 '3',
 "Harry Potter and the Philosopher's Stone",
 'Rowling, J.K.',
 '4,200,654',
 'Bloomsbury',
 '4',
 'Harry Potter and the Order of the Phoenix',
 'Rowling, J.K.',
 '4,179,479',
 'Bloomsbury',
 '5',
 'Fifty Shades of Grey',
 'James, E. L.',
 '3,758,936',
 'Random House',
 '6',
 'Harry Potter and the Goblet of Fire',
 'Rowling, J.K.',
 '3,583,215',
 'Bloomsbury',
 '7',
 'Harry Potter and the Chamber of Secrets',
 'Rowling, J.K.',
 '3,484,047',
 'Bloomsbury',
 '8',
 'Harry Potter and the Prisoner of Azkaban',
 'Rowling, J.K.',
 '3,377,906',
 'Bloomsbury',
 '9',
 'Angels and Demons',
 'Brown, Dan',
 '3,193,946',
 'Transworld',
 '10',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Rowling, J.K.',
 '2,950,264',
 'Bloomsbury',
 '11',
 'Fifty Shades Darker',
 'James, E. L.',
 '2,479,784',
 'Random House',
 '12',
 'Twilight',
 'Meyer, Stephenie',
 '2,315,405',
 'Little, Brown Book',
 '13',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Larsson, Stieg',
 '2,233,570',
 'Quercus',
 '14',
 'Fifty Shades Freed',
 'James, E. L.',
 '2,193,928',
 'Random House',
 '15',
 'Lost Symbol,The',
 'Brown, Dan',
 '2,183,031',
 'Transworld',
 '16',
 'New Moon',
 'Meyer, Stephenie',
 '2,152,737',
 'Little, Brown Book',
 '17',
 'Deception Point',
 'Brown, Dan',
 '2,062,145',
 'Transworld',
 '18',
 'Eclipse',
 'Meyer, Stephenie',
 '2,052,876',
 'Little, Brown Book',
 '19',
 'Lovely Bones,The',
 'Sebold, Alice',
 '2,005,598',
 'Pan Macmillan',
 '20',
 'Curious Incident of the Dog in the Night-time,The',
 'Haddon, Mark',
 '1,979,552',
 'Random House',
 '21',
 'Digital Fortress',
 'Brown, Dan',
 '1,928,900',
 'Transworld',
 '22',
 'Short History of Nearly Everything,A',
 'Bryson, Bill',
 '1,852,919',
 'Transworld',
 '23',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Larsson, Stieg',
 '1,814,784',
 'Quercus',
 '24',
 'Breaking Dawn',
 'Meyer, Stephenie',
 '1,787,118',
 'Little, Brown Book',
 '25',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Carle, Eric',
 '1,783,535',
 'Penguin',
 '26',
 'Gruffalo,The',
 'Donaldson, Julia',
 '1,781,269',
 'Pan Macmillan',
 '27',
 "Jamie's 30-Minute Meals",
 'Oliver, Jamie',
 '1,743,266',
 'Penguin',
 '28',
 'Kite Runner,The',
 'Hosseini, Khaled',
 '1,629,119',
 'Bloomsbury',
 '29',
 'One Day',
 'Nicholls, David',
 '1,616,068',
 'Hodder & Stoughton',
 '30',
 'Thousand Splendid Suns,A',
 'Hosseini, Khaled',
 '1,583,992',
 'Bloomsbury',
 '31',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 'Larsson, Stieg',
 '1,555,135',
 'Quercus',
 '32',
 "Time Traveler's Wife,The",
 'Niffenegger, Audrey',
 '1,546,886',
 'Random House',
 '33',
 'Atonement',
 'McEwan, Ian',
 '1,539,428',
 'Random House',
 '34',
 "Bridget Jones's Diary:A Novel",
 'Fielding, Helen',
 '1,508,205',
 'Pan Macmillan',
 '35',
 'World According to Clarkson,The',
 'Clarkson, Jeremy',
 '1,489,403',
 'Penguin',
 '36',
 "Captain Corelli's Mandolin",
 'Bernieres, Louis de',
 '1,352,318',
 'Random House',
 '37',
 'Sound of Laughter,The',
 'Kay, Peter',
 '1,310,207',
 'Random House',
 '38',
 'Life of Pi',
 'Martel, Yann',
 '1,310,176',
 'Canongate',
 '39',
 'Billy Connolly',
 'Stephenson, Pamela',
 '1,231,957',
 'HarperCollins',
 '40',
 'Child Called It,A',
 'Pelzer, Dave',
 '1,217,712',
 'Orion',
 '41',
 "Gruffalo's Child,The",
 'Donaldson, Julia',
 '1,208,711',
 'Pan Macmillan',
 '42',
 "Angela's Ashes:A Memoir of a Childhood",
 'McCourt, Frank',
 '1,204,058',
 'HarperCollins',
 '43',
 'Birdsong',
 'Faulks, Sebastian',
 '1,184,967',
 'Random House',
 '44',
 'Northern Lights:His Dark Materials S.',
 'Pullman, Philip',
 '1,181,503',
 'Scholastic Ltd.',
 '45',
 'Labyrinth',
 'Mosse, Kate',
 '1,181,093',
 'Orion',
 '46',
 'Harry Potter and the Half-blood Prince',
 'Rowling, J.K.',
 '1,153,181',
 'Bloomsbury',
 '47',
 'Help,The',
 'Stockett, Kathryn',
 '1,132,336',
 'Penguin',
 '48',
 'Man and Boy',
 'Parsons, Tony',
 '1,130,802',
 'HarperCollins',
 '49',
 'Memoirs of a Geisha',
 'Golden, Arthur',
 '1,126,337',
 'Random House',
 '50',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'McCall Smith, Alexander',
 '1,115,549',
 'Little, Brown Book',
 '51',
 'Island,The',
 'Hislop, Victoria',
 '1,108,328',
 'Headline',
 '52',
 'PS, I Love You',
 'Ahern, Cecelia',
 '1,107,379',
 'HarperCollins',
 '53',
 'You are What You Eat:The Plan That Will Change Your Life',
 'McKeith, Gillian',
 '1,104,403',
 'Penguin',
 '54',
 'Shadow of the Wind,The',
 'Zafon, Carlos Ruiz',
 '1,092,349',
 'Orion',
 '55',
 'Tales of Beedle the Bard,The',
 'Rowling, J.K.',
 '1,090,847',
 'Bloomsbury',
 '56',
 'Broker,The',
 'Grisham, John',
 '1,087,262',
 'Random House',
 '57',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Atkins, Robert C.',
 '1,054,196',
 'Random House',
 '58',
 'Subtle Knife,The:His Dark Materials S.',
 'Pullman, Philip',
 '1,037,160',
 'Scholastic Ltd.',
 '59',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 'Truss, Lynne',
 '1,023,688',
 'Profile Books Group',
 '60',
 "Delia's How to Cook:(Bk.1)",
 'Smith, Delia',
 '1,015,956',
 'Random House',
 '61',
 'Chocolat',
 'Harris, Joanne',
 '1,009,873',
 'Transworld',
 '62',
 'Boy in the Striped Pyjamas,The',
 'Boyne, John',
 '1,004,414',
 'Random House Childrens Books G',
 '63',
 "My Sister's Keeper",
 'Picoult, Jodi',
 '1,003,780',
 'Hodder & Stoughton',
 '64',
 'Amber Spyglass,The:His Dark Materials S.',
 'Pullman, Philip',
 '1,002,314',
 'Scholastic Ltd.',
 '65',
 'To Kill a Mockingbird',
 'Lee, Harper',
 '998,213',
 'Random House',
 '66',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Gray, John',
 '992,846',
 'HarperCollins',
 '67',
 'Dear Fatty',
 'French, Dawn',
 '986,753',
 'Random House',
 '68',
 'Short History of Tractors in Ukrainian,A',
 'Lewycka, Marina',
 '986,115',
 'Penguin',
 '69',
 'Hannibal',
 'Harris, Thomas',
 '970,509',
 'Random House',
 '70',
 'Lord of the Rings,The',
 'Tolkien, J. R. R.',
 '967,466',
 'HarperCollins',
 '71',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Moore, Michael',
 '963,353',
 'Penguin',
 '72',
 'Interpretation of Murder,The',
 'Rubenfeld, Jed',
 '962,515',
 'Headline',
 '73',
 'Sharon Osbourne Extreme:My Autobiography',
 'Osbourne, Sharon',
 '959,496',
 'Little, Brown Book',
 '74',
 'Alchemist,The:A Fable About Following Your Dream',
 'Coelho, Paulo',
 '956,114',
 'HarperCollins',
 '75',
 "At My Mother's Knee ...:and Other Low Joints",
 "O'Grady, Paul",
 '945,640',
 'Transworld',
 '76',
 'Notes from a Small Island',
 'Bryson, Bill',
 '931,312',
 'Transworld',
 '77',
 'Return of the Naked Chef,The',
 'Oliver, Jamie',
 '925,425',
 'Penguin',
 '78',
 'Bridget Jones: The Edge of Reason',
 'Fielding, Helen',
 '924,695',
 'Pan Macmillan',
 '79',
 "Jamie's Italy",
 'Oliver, Jamie',
 '906,968',
 'Penguin',
 '80',
 'I Can Make You Thin',
 'McKenna, Paul',
 '905,086',
 'Transworld',
 '81',
 'Down Under',
 'Bryson, Bill',
 '890,847',
 'Transworld',
 '82',
 'Summons,The',
 'Grisham, John',
 '869,671',
 'Random House',
 '83',
 'Small Island',
 'Levy, Andrea',
 '869,659',
 'Headline',
 '84',
 'Nigella Express',
 'Lawson, Nigella',
 '862,602',
 'Random House',
 '85',
 'Brick Lane',
 'Ali, Monica',
 '856,540',
 'Transworld',
 '86',
 "Memory Keeper's Daughter,The",
 'Edwards, Kim',
 '845,858',
 'Penguin',
 '87',
 'Room on the Broom',
 'Donaldson, Julia',
 '842,535',
 'Pan Macmillan',
 '88',
 'About a Boy',
 'Hornby, Nick',
 '828,215',
 'Penguin',
 '89',
 'My Booky Wook',
 'Brand, Russell',
 '820,563',
 'Hodder & Stoughton',
 '90',
 'God Delusion,The',
 'Dawkins, Richard',
 '816,907',
 'Transworld',
 '91',
 '"Beano" Annual,The',
 '0',
 '816,585',
 'D.C. Thomson',
 '92',
 'White Teeth',
 'Smith, Zadie',
 '815,586',
 'Penguin',
 '93',
 'House at Riverton,The',
 'Morton, Kate',
 '814,370',
 'Pan Macmillan',
 '94',
 'Book Thief,The',
 'Zusak, Markus',
 '809,641',
 'Transworld',
 '95',
 'Nights of Rain and Stars',
 'Binchy, Maeve',
 '808,900',
 'Orion',
 '96',
 'Ghost,The',
 'Harris, Robert',
 '807,311',
 'Random House',
 '97',
 'Happy Days with the Naked Chef',
 'Oliver, Jamie',
 '794,201',
 'Penguin',
 '98',
 'Hunger Games,The:Hunger Games Trilogy',
 'Collins, Suzanne',
 '792,187',
 'Scholastic Ltd.',
 '99',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 'Pelzer, Dave',
 '791,507',
 'Orion',
 '100',
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours",
 'Oliver, Jamie',
 '791,095',
 'Penguin']

In [117]:
Book=Table[1:500:5] #Slicing book name

In [118]:
Book_Name=pd.DataFrame(Book)

In [121]:
Author=Table[2:500:5] #Slicing author name

In [122]:
Author_Name=pd.DataFrame(Author)

In [124]:
Volume=Table[3:500:5] #Slicing volume sold

In [126]:
Volume_Sold=pd.DataFrame(Volume)

In [128]:
Publish=Table[4:500:5] #Slicing publisher name

In [130]:
Publisher_Name=pd.DataFrame(Publish)

In [132]:
Novel=pd.concat([Book_Name,Author_Name,Volume_Sold,Publisher_Name,Genres],axis=1)
Novel.columns=['Book_Name','Author_Name','Volume_Sold','Publisher_Name','Genre']
Novel

,Book_Name,Author_Name,Volume_Sold,Publisher_Name,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# TV Series

In [133]:
driver.get("https://www.imdb.com/list/ls095964455/")

In [137]:
Name=[]
Name_Tag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']")
for i in Name_Tag:
    Name.append(i.text.split('(')[0])
Name

['1. Game of Thrones ',
 '2. Stranger Things ',
 '3. The Walking Dead ',
 '4. 13 Reasons Why ',
 '5. The 100 ',
 '6. Orange Is the New Black ',
 '7. Riverdale ',
 "8. Grey's Anatomy ",
 '9. The Flash ',
 '10. Arrow ',
 '11. Money Heist ',
 '12. The Big Bang Theory ',
 '13. Black Mirror ',
 '14. Sherlock ',
 '15. Vikings ',
 '16. Pretty Little Liars ',
 '17. The Vampire Diaries ',
 '18. American Horror Story ',
 '19. Breaking Bad ',
 '20. Lucifer ',
 '21. Supernatural ',
 '22. Prison Break ',
 '23. How to Get Away with Murder ',
 '24. Teen Wolf ',
 '25. The Simpsons ',
 '26. Once Upon a Time ',
 '27. Narcos ',
 '28. Daredevil ',
 '29. Friends ',
 '30. How I Met Your Mother ',
 '31. Suits ',
 '32. Mr. Robot ',
 '33. The Originals ',
 '34. Supergirl ',
 '35. Gossip Girl ',
 '36. Sense8 ',
 '37. Gotham ',
 '38. Westworld ',
 '39. Jessica Jones ',
 '40. Modern Family ',
 '41. Rick and Morty ',
 '42. Shadowhunters ',
 '43. The End of the F***ing World ',
 '44. House of Cards ',
 '45. Dark ',
 '46. Elite ',
 '47. Sex Education ',
 '48. Shameless ',
 '49. New Girl ',
 '50. Agents of S.H.I.E.L.D. ',
 '51. You ',
 '52. Dexter ',
 '53. Fear the Walking Dead ',
 '54. Family Guy ',
 '55. The Blacklist ',
 '56. Lost ',
 '57. Peaky Blinders ',
 '58. House ',
 '59. Quantico ',
 '60. Orphan Black ',
 '61. Homeland ',
 '62. Blindspot ',
 "63. DC's Legends of Tomorrow ",
 "64. The Handmaid's Tale ",
 '65. Chilling Adventures of Sabrina ',
 '66. The Good Doctor ',
 '67. Jane the Virgin ',
 '68. Glee ',
 '69. South Park ',
 '70. Brooklyn Nine-Nine ',
 '71. Under the Dome ',
 '72. The Umbrella Academy ',
 '73. True Detective ',
 '74. The OA ',
 '75. Desperate Housewives ',
 '76. Better Call Saul ',
 '77. Bates Motel ',
 '78. The Punisher ',
 '79. Atypical ',
 '80. Dynasty ',
 '81. This Is Us ',
 '82. The Good Place ',
 '83. Iron Fist ',
 '84. The Rain ',
 '85. Mindhunter ',
 '86. Revenge ',
 '87. Luke Cage ',
 '88. Scandal ',
 '89. The Defenders ',
 '90. Big Little Lies ',
 '91. Insatiable ',
 '92. The Mentalist ',
 '93. The Crown ',
 '94. Chernobyl ',
 '95. iZombie ',
 '96. Reign ',
 '97. A Series of Unfortunate Events ',
 '98. Criminal Minds ',
 '99. Scream: The TV Series ',
 '100. The Haunting of Hill House ']

In [140]:
Names=pd.DataFrame(Name)

In [141]:
Time=[]
Time_Tag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']")
for i in Time_Tag:
    Time.append(i.text.split('(')[1].replace(')',''))
Time

['2011–2019',
 '2016– ',
 '2010–2022',
 '2017–2020',
 '2014–2020',
 '2013–2019',
 '2017– ',
 '2005– ',
 '2014– ',
 '2012–2020',
 '2017–2021',
 '2007–2019',
 '2011–2019',
 '2010–2017',
 '2013–2020',
 '2010–2017',
 '2009–2017',
 '2011– ',
 '2008–2013',
 '2016–2021',
 '2005–2020',
 '2005–2017',
 '2014–2020',
 '2011–2017',
 '1989– ',
 '2011–2018',
 '2015–2017',
 '2015–2018',
 '1994–2004',
 '2005–2014',
 '2011–2019',
 '2015–2019',
 '2013–2018',
 '2015–2021',
 '2007–2012',
 '2015–2018',
 '2014–2019',
 '2016– ',
 '2015–2019',
 '2009–2020',
 '2013– ',
 '2016–2019',
 '2017–2019',
 '2013–2018',
 '2017–2020',
 '2018– ',
 '2019– ',
 '2011–2021',
 '2011–2018',
 '2013–2020',
 '2018– ',
 '2006–2013',
 '2015– ',
 '1999– ',
 '2013– ',
 '2004–2010',
 '2013–2022',
 '2004–2012',
 '2015–2018',
 '2013–2017',
 '2011–2020',
 '2015–2020',
 '2016–2022',
 '2017– ',
 '2018–2020',
 '2017– ',
 '2014–2019',
 '2009–2015',
 '1997– ',
 '2013–2021',
 '2013–2015',
 '2019–2022',
 '2014–2019',
 '2016–2019',
 '2004–2012',
 '2015–2022',
 '2013–2017',
 '2017–2019',
 '2017–2021',
 '2017–2022',
 '2016–2022',
 '2016–2020',
 '2017–2018',
 '2018–2020',
 '2017–2019',
 '2011–2015',
 '2016–2018',
 '2012–2018',
 '2017',
 '2017–2019',
 '2018–2019',
 '2008–2015',
 '2016– ',
 '2019',
 '2015–2019',
 '2013–2017',
 '2017–2019',
 '2005–2020',
 '2015–2019',
 '2018']

In [143]:
Year_Span=pd.DataFrame(Time)

In [144]:
Genre=[]
Genre_Tag=driver.find_elements_by_xpath("//span[@class='genre']")
for i in Genre_Tag:
    Genre.append(i.text)
Genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Sci-Fi',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [145]:
Genres=pd.DataFrame(Genre)

In [146]:
Run=[]
Run_Tag=driver.find_elements_by_xpath("//span[@class='runtime']")
for i in Run_Tag:
    Run.append(i.text)
Run

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [147]:
Run_Time=pd.DataFrame(Run)

In [148]:
Rating=[]
Rating_Tag=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']")
for i in Rating_Tag:
    Rating.append(i.text)
Rating

['9.2',
 '8.7',
 '8.2',
 '7.5',
 '7.6',
 '8.1',
 '6.6',
 '7.6',
 '7.6',
 '7.5',
 '8.2',
 '8.2',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.5',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.7',
 '8.7',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.5',
 '8.6',
 '8.3',
 '6.2',
 '7.4',
 '8.2',
 '7.8',
 '8.6',
 '7.9',
 '8.5',
 '9.2',
 '6.5',
 '8.1',
 '8.7',
 '8.7',
 '7.4',
 '8.4',
 '8.6',
 '7.7',
 '7.5',
 '7.7',
 '8.7',
 '6.8',
 '8.2',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.6',
 '8.3',
 '8.3',
 '7.3',
 '6.7',
 '8.4',
 '7.4',
 '8.1',
 '7.9',
 '6.8',
 '8.7',
 '8.4',
 '6.5',
 '8',
 '8.9',
 '7.8',
 '7.6',
 '8.8',
 '8.2',
 '8.5',
 '8.3',
 '7.2',
 '8.7',
 '8.2',
 '6.4',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.2',
 '8.5',
 '6.5',
 '8.1',
 '8.7',
 '9.4',
 '7.8',
 '7.4',
 '7.8',
 '8.1',
 '7.1',
 '8.6']

In [149]:
Ratings=pd.DataFrame(Rating)

In [150]:
Vote=[]
Vote_Tag=driver.find_elements_by_xpath("//p[@class='text-muted text-small']")
for i in Vote_Tag:
    Vote.append(i.text)
Vote

['TV-MA | 57 min | Action, Adventure, Drama',
 'Stars: Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
 'Votes: 2,009,458',
 'TV-14 | 51 min | Drama, Fantasy, Horror',
 'Stars: Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
 'Votes: 1,090,617',
 'TV-MA | 44 min | Drama, Horror, Thriller',
 'Stars: Andrew Lincoln, Norman Reedus, Melissa McBride, Lauren Cohan',
 'Votes: 955,155',
 'TV-MA | 60 min | Drama, Mystery, Thriller',
 'Stars: Dylan Minnette, Katherine Langford, Christian Navarro, Alisha Boe',
 'Votes: 285,549',
 'TV-14 | 43 min | Drama, Mystery, Sci-Fi',
 'Stars: Eliza Taylor, Bob Morley, Marie Avgeropoulos, Isaiah Washington',
 'Votes: 245,207',
 'TV-MA | 59 min | Comedy, Crime, Drama',
 'Stars: Taylor Schilling, Danielle Brooks, Taryn Manning, Emma Myles',
 'Votes: 297,686',
 'TV-14 | 45 min | Crime, Drama, Mystery',
 'Stars: Lili Reinhart, Camila Mendes, Cole Sprouse, K.J. Apa',
 'Votes: 140,896',
 'TV-14 | 41 min | Drama, Romance',
 'Stars: Ellen Pompeo, Chandra Wilson, James Pickens Jr., Justin Chambers',
 'Votes: 298,521',
 'TV-PG | 43 min | Action, Adventure, Drama',
 'Stars: Grant Gustin, Candice Patton, Danielle Panabaker, Carlos Valdes',
 'Votes: 340,866',
 'TV-14 | 42 min | Action, Adventure, Crime',
 'Stars: Stephen Amell, Katie Cassidy, David Ramsey, Susanna Thompson',
 'Votes: 427,601',
 'TV-MA | 70 min | Action, Crime, Drama',
 'Stars: Úrsula Corberó, Álvaro Morte, Itziar Ituño, Pedro Alonso',
 'Votes: 462,404',
 'TV-PG | 22 min | Comedy, Romance',
 'Stars: Johnny Galecki, Jim Parsons, Kaley Cuoco, Simon Helberg',
 'Votes: 789,172',
 'TV-MA | 60 min | Drama, Mystery, Sci-Fi',
 'Stars: Daniel Lapaine, Hannah John-Kamen, Michaela Coel, Beatrice Robertson-Jones',
 'Votes: 525,004',
 'TV-14 | 88 min | Crime, Drama, Mystery',
 'Stars: Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves',
 'Votes: 901,547',
 'TV-MA | 44 min | Action, Adventure, Drama',
 'Stars: Katheryn Winnick, Gustaf Skarsgård, Alexander Ludwig, Georgia Hirst',
 'Votes: 515,160',
 'TV-14 | 44 min | Drama, Mystery, Romance',
 'Stars: Troian Bellisario, Ashley Benson, Lucy Hale, Shay Mitchell',
 'Votes: 164,525',
 'TV-14 | 43 min | Drama, Fantasy, Horror',
 'Stars: Nina Dobrev, Paul Wesley, Ian Somerhalder, Kat Graham',
 'Votes: 313,945',
 'TV-MA | 60 min | Drama, Horror, Sci-Fi',
 'Stars: Lady Gaga, Kathy Bates, Angela Bassett, Sarah Paulson',
 'Votes: 309,182',
 'TV-MA | 49 min | Crime, Drama, Thriller',
 'Stars: Bryan Cranston, Aaron Paul, Anna Gunn, Betsy Brandt',
 'Votes: 1,769,273',
 'TV-14 | 42 min | Crime, Drama, Fantasy',
 'Stars: Tom Ellis, Lauren German, Kevin Alejandro, D.B. Woodside',
 'Votes: 312,442',
 'TV-14 | 44 min | Drama, Fantasy, Horror',
 'Stars: Jared Padalecki, Jensen Ackles, Jim Beaver, Misha Collins',
 'Votes: 433,293',
 'TV-14 | 44 min | Action, Crime, Drama',
 'Stars: Dominic Purcell, Wentworth Miller, Amaury Nolasco, Robert Knepper',
 'Votes: 522,261',
 'TV-14 | 43 min | Crime, Drama, Mystery',
 'Stars: Viola Davis, Billy Brown, Jack Falahee, Aja Naomi King',
 'Votes: 148,401',
 'TV-14 | 41 min | Action, Drama, Fantasy',
 "Stars: Tyler Posey, Holland Roden, Dylan O'Brien, Linden Ashby",
 'Votes: 144,540',
 'TV-14 | 22 min | Animation, Comedy',
 'Stars: Dan Castellaneta, Nancy Cartwright, Harry Shearer, Julie Kavner',
 'Votes: 398,625',
 'TV-PG | 60 min | Adventure, Fantasy, Romance',
 'Stars: Ginnifer Goodwin, Jennifer Morrison, Lana Parrilla, Robert Carlyle',
 'Votes: 221,742',
 'TV-MA | 49 min | Biography, Crime, Drama',
 'Stars: Pedro Pascal, Wagner Moura, Boyd Holbrook, Alberto Ammann',
 'Votes: 409,724',
 'TV-MA | 54 min | Action, Crime, Drama',
 "Stars: Charlie Cox, Vincent D'Onofrio, Deborah Ann Woll, Elden Henson",
 'Votes: 425,334',
 'TV-14 | 22 min | Comedy, Romance',
 'Stars: Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc',
 'Votes: 963,128',
 'TV-14 | 22 min | Comedy, Romance',
 'Stars: Josh Radnor, Jason Segel, Cobie Smulders, Neil Patrick Harris',
 'Votes: 668,551',
 'TV-14 | 44 min | Comedy, Drama',
 'Stars: Gabriel Macht, Patrick J. Adams, Meghan Markle, Sarah Rafferty',
 'Votes: 400,304',
 'TV-MA | 49 min | Crime, Drama, Thriller',
 'Stars: Rami Malek, Christian Slater, Carly Chaikin, Martin Wallström',
 'Votes: 377,808',
 'TV-14 | 45 min | Drama, Fantasy, Horror',
 'Stars: Joseph Morgan, Daniel Gillies, Claire Holt, Phoebe Tonkin',
 'Votes: 133,219',
 'TV-PG | 43 min | Action, Adventure, Drama',
 'Stars: Melissa Benoist, Chyler Leigh, David Harewood, Katie McGrath',
 'Votes: 122,794',
 'TV-14 | 42 min | Drama, Romance',
 'Stars: Blake Lively, Leighton Meester, Penn Badgley, Ed Westwick',
 'Votes: 171,202',
 'TV-MA | 60 min | Drama, Mystery, Sci-Fi',
 'Stars: Bae Doona, Jamie Clayton, Tina Desai, Tuppence Middleton',
 'Votes: 152,701',
 'TV-14 | 42 min | Action, Crime, Drama',
 'Stars: Ben McKenzie, Jada Pinkett Smith, Donal Logue, Camren Bicondova',
 'Votes: 227,557',
 'TV-MA | 62 min | Drama, Mystery, Sci-Fi',
 'Stars: Evan Rachel Wood, Jeffrey Wright, Ed Harris, Thandiwe Newton',
 'Votes: 484,482',
 'TV-MA | 56 min | Action, Crime, Drama',
 'Stars: Krysten Ritter, Rachael Taylor, Eka Darville, Carrie-Anne Moss',
 'Votes: 210,808',
 'TV-PG | 22 min | Comedy, Drama, Romance',
 "Stars: Ed O'Neill, Sofía Vergara, Julie Bowen, Ty Burrell",
 'Votes: 415,707',
 'TV-MA | 23 min | Animation, Adventure, Comedy',
 'Stars: Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke',
 'Votes: 484,440',
 'TV-14 | 42 min | Action, Drama, Fantasy',
 'Stars: Katherine McNamara, Dominic Sherwood, Alberto Rosende, Matthew Daddario',
 'Votes: 62,008',
 'TV-MA | 25 min | Adventure, Comedy, Crime',
 'Stars: Jessica Barden, Alex Lawther, Steve Oram, Christine Bottomley',
 'Votes: 181,725',
 'TV-MA | 51 min | Drama',
 'Stars: Kevin Spacey, Michel Gill, Robin Wright, Kate Mara',
 'Votes: 497,201',
 'TV-MA | 60 min | Crime, Drama, Mystery',
 'Stars: Louis Hofmann, Karoline Eichhorn, Lisa Vicari, Maja Schöne',
 'Votes: 362,378',
 'TV-MA | 60 min | Crime, Drama, Thriller',
 'Stars: Itzan Escamilla, Omar Ayuso, Miguel Bernardeau, Arón Piper',
 'Votes: 75,086',
 'TV-MA | 45 min | Comedy, Drama',
 'Stars: Asa Butterfield, Gillian Anderson, Emma Mackey, Ncuti Gatwa',
 'Votes: 266,067',
 'TV-MA | 46 min | Comedy, Drama',
 'Stars: Emmy Rossum, William H. Macy, Ethan Cutkosky, Jeremy Allen White',
 'Votes: 233,499',
 'TV-14 | 22 min | Comedy, Romance',
 'Stars: Zooey Deschanel, Jake Johnson, Max Greenfield, Hannah Simone',
 'Votes: 218,728',
 'TV-PG | 45 min | Action, Adventure, Drama',
 'Stars: Clark Gregg, Ming-Na Wen, Brett Dalton, Iain De Caestecker',
 'Votes: 214,951',
 'TV-MA | 45 min | Crime, Drama, Romance',
 'Stars: Penn Badgley, Victoria Pedretti, Ambyr Childers, Elizabeth Lail',
 'Votes: 229,557',
 'TV-MA | 53 min | Crime, Drama, Mystery',
 'Stars: Michael C. Hall, Jennifer Carpenter, David Zayas, James Remar',
 'Votes: 715,836',
 'TV-MA | 44 min | Drama, Horror, Sci-Fi',
 'Stars: Kim Dickens, Frank Dillane, Cliff Curtis, Rubén Blades',
 'Votes: 128,180',
 'TV-MA | 22 min | Animation, Comedy',
 'Stars: Seth MacFarlane, Alex Borstein, Seth Green, Mila Kunis',
 'Votes: 330,908',
 'TV-14 | 43 min | Crime, Drama, Mystery',
 'Stars: James Spader, Megan Boone, Diego Klattenhoff, Ryan Eggold',
 'Votes: 242,233',
 'TV-14 | 44 min | Adventure, Drama, Fantasy',
 'Stars: Jorge Garcia, Josh Holloway, Yunjin Kim, Evangeline Lilly',
 'Votes: 541,298',
 'TV-MA | 60 min | Crime, Drama',
 'Stars: Cillian Murphy, Paul Anderson, Sophie Rundle, Helen McCrory',
 'Votes: 508,686',
 'TV-14 | 44 min | Drama, Mystery',
 'Stars: Hugh Laurie, Omar Epps, Robert Sean Leonard, Jesse Spencer',
 'Votes: 452,663',
 'TV-14 | 42 min | Crime, Drama, Mystery',
 'Stars: Priyanka Chopra Jonas, Jake McLaughlin, Johanna Braddy, Aunjanue Ellis',
 'Votes: 60,601',
 'TV-MA | 44 min | Drama, Sci-Fi, Thriller',
 'Stars: Tatiana Maslany, Dylan Bruce, Jordan Gavaris, Kevin Hanchard',
 'Votes: 109,502',
 'TV-MA | 55 min | Crime, Drama, Mystery',
 'Stars: Claire Danes, Mandy Patinkin, Damian Lewis, Rupert Friend',
 'Votes: 337,082',
 'TV-14 | 42 min | Action, Crime, Drama',
 'Stars: Sullivan Stapleton, Jaimie Alexander, Audrey Esparza, Ashley Johnson',
 'Votes: 73,006',
 'TV-14 | 42 min | Action, Adventure, Drama',
 'Stars: Caity Lotz, Amy Louise Pemberton, Dominic Purcell, Nick Zano',
 'Votes: 103,561',
 'TV-MA | 60 min | Drama, Thriller',
 'Stars: Elisabeth Moss, Yvonne Strahovski, Joseph Fiennes, Ann Dowd',
 'Votes: 220,121',
 'TV-14 | 60 min | Drama, Fantasy, Horror',
 'Stars: Kiernan Shipka, Ross Lynch, Lucy Davis, Chance Perdomo',
 'Votes: 91,755',
 'TV-14 | 41 min | Drama',
 'Stars: Freddie Highmore, Hill Harper, Richard Schiff, Christina Chang',
 'Votes: 90,876',
 'TV-PG | 60 min | Comedy',
 'Stars: Gina Rodriguez, Andrea Navedo, Yael Grobglas, Justin Baldoni',
 'Votes: 48,763',
 'TV-PG | 44 min | Comedy, Drama, Music',
 'Stars: Lea Michele, Jane Lynch, Matthew Morrison, Cory Monteith',
 'Votes: 146,786',
 'TV-MA | 22 min | Animation, Comedy',
 'Stars: Trey Parker, Matt Stone, Isaac Hayes, Mona Marshall',
 'Votes: 362,721',
 'TV-14 | 22 min | Comedy, Crime',
 'Stars: Andy Samberg, Stephanie Beatriz, Terry Crews, Melissa Fumero',
 'Votes: 300,100',
 'TV-14 | 43 min | Drama, Mystery, Sci-Fi',
 'Stars: Mike Vogel, Rachelle Lefevre, Alexander Koch, Colin Ford',
 'Votes: 105,884',
 'TV-14 | 60 min | Action, Adventure, Comedy',
 'Stars: Elliot Page, Tom Hopper, David Castañeda, Emmy Raver-Lampman',
 'Votes: 226,507',
 'TV-MA | 55 min | Crime, Drama, Mystery',
 'Stars: Vince Vaughn, Colin Farrell, Rachel McAdams, Taylor Kitsch',
 'Votes: 553,510',
 'TV-MA | 60 min | Drama, Fantasy, Mystery',
 'Stars: Brit Marling, Jason Isaacs, Scott Wilson, Alice Krige',
 'Votes: 102,992',
 'TV-14 | 45 min | Comedy, Drama, Mystery',
 'Stars: Teri Hatcher, Felicity Huffman, Marcia Cross, Eva Longoria',
 'Votes: 126,984',
 'TV-MA | 46 min | Crime, Drama',
 'Stars: Bob Odenkirk, Rhea Seehorn, Jonathan Banks, Michael Mando',
 'Votes: 433,050',
 'TV-MA | 45 min | Drama, Horror, Mystery',
 'Stars: Vera Farmiga, Freddie Highmore, Max Thieriot, Nicola Peltz Beckham',
 'Votes: 106,153',
 'TV-MA | 53 min | Action, Crime, Drama',
 'Stars: Jon Bernthal, Amber Rose Revah, Ben Barnes, Jason R. Moore',
 'Votes: 224,922',
 'TV-MA | 30 min | Comedy, Drama',
 'Stars: Jennifer Jason Leigh, Keir Gilchrist, Brigette Lundy-Paine, Michael Rapaport',
 'Votes: 85,053',
 'TV-14 | 42 min | Drama',
 'Stars: Elizabeth Gillies, Rafael de la Fuente, Robert Christopher Riley, Sam Adegoke',
 'Votes: 21,588',
 'TV-14 | 45 min | Comedy, Drama, Romance',
 'Stars: Milo Ventimiglia, Mandy Moore, Sterling K. Brown, Chrissy Metz',
 'Votes: 139,136',
 'TV-PG | 22 min | Comedy, Drama, Fantasy',
 "Stars: Kristen Bell, William Jackson Harper, Jameela Jamil, D'Arcy Carden",
 'Votes: 152,373',
 'TV-MA | 55 min | Action, Adventure, Crime',
 'Stars: Finn Jones, Jessica Henwick, Jessica Stroup, Tom Pelphrey',
 'Votes: 128,399',
 'TV-MA | 45 min | Drama, Sci-Fi, Thriller',
 'Stars: Alba August, Lucas Lynggaard Tønnesen, Mikkel Boe Følsgaard, Lukas Løkken',
 'Votes: 36,347',
 'TV-MA | 60 min | Crime, Drama, Mystery',
 'Stars: Jonathan Groff, Holt McCallany, Anna Torv, Hannah Gross',
 'Votes: 274,473',
 'TV-14 | 44 min | Drama, Mystery, Thriller',
 'Stars: Madeleine Stowe, Emily VanCamp, Gabriel Mann, Nick Wechsler',
 'Votes: 119,336',
 'TV-MA | 55 min | Action, Crime, Drama',
 'Stars: Mike Colter, Simone Missick, Theo Rossi, Alfre Woodard',
 'Votes: 128,772',
 'TV-14 | 43 min | Drama, Thriller',
 'Stars: Kerry Washington, Darby Stanchfield, Katie Lowes, Guillermo Díaz',
 'Votes: 72,991',
 'TV-MA | 50 min | Action, Adventure, Crime',
 'Stars: Charlie Cox, Krysten Ritter, Mike Colter, Finn Jones',
 'Votes: 104,865',
 'TV-MA | 60 min | Crime, Drama, Mystery',
 'Stars: Reese Witherspoon, Nicole Kidman, Shailene Woodley, Zoë Kravitz',
 'Votes: 192,025',
 'TV-MA | 45 min | Comedy, Drama, Thriller',
 'Stars: Dallas Roberts, Debby Ryan, Christopher Gorham, Kimmy Shields',
 'Votes: 27,923',
 'TV-14 | 43 min | Crime, Drama, Mystery',
 'Stars: Simon Baker, Robin Tunney, Tim Kang, Owain Yeoman',
 'Votes: 181,633',
 'TV-MA | 58 min | Biography, Drama, History',
 'Stars: Claire Foy, Olivia Colman, Imelda Staunton, Matt Smith',
 'Votes: 193,848',
 'TV-MA | 330 min | Drama, History, Thriller',
 'Stars: Jessie Buckley, Jared Harris, Stellan Skarsgård, Adam Nagaitis',
 'Votes: 713,029',
 'TV-14 | 42 min | Comedy, Crime, Drama',
 'Stars: Rose McIver, Malcolm Goodwin, Rahul Kohli, Robert Buckley',
 'Votes: 67,122',
 'TV-14 | 42 min | Drama',
 'Stars: Adelaide Kane, Megan Follows, Celina Sinden, Torrance Coombs',
 'Votes: 49,098',
 'TV-PG | 50 min | Adventure, Comedy, Drama',
 'Stars: Neil Patrick Harris, Patrick Warburton, Malina Weissman, Louis Hynes',
 'Votes: 59,894',
 'TV-14 | 42 min | Crime, Drama, Mystery',
 'Stars: Matthew Gray Gubler, Kirsten Vangsness, A.J. Cook, Joe Mantegna',
 'Votes: 192,255',
 'TV-14 | 45 min | Comedy, Crime, Drama',
 'Stars: Willa Fitzgerald, Bex Taylor-Klaus, John Karna, Carlson Young',
 'Votes: 40,598',
 'TV-MA | 572 min | Drama, Horror, Mystery',
 'Stars: Michiel Huisman, Carla Gugino, Henry Thomas, Elizabeth Reaser',
 'Votes: 231,253']

In [152]:
Vote1=Vote[2:300:3]
Vote1 #Slicing vote

['Votes: 2,009,458',
 'Votes: 1,090,617',
 'Votes: 955,155',
 'Votes: 285,549',
 'Votes: 245,207',
 'Votes: 297,686',
 'Votes: 140,896',
 'Votes: 298,521',
 'Votes: 340,866',
 'Votes: 427,601',
 'Votes: 462,404',
 'Votes: 789,172',
 'Votes: 525,004',
 'Votes: 901,547',
 'Votes: 515,160',
 'Votes: 164,525',
 'Votes: 313,945',
 'Votes: 309,182',
 'Votes: 1,769,273',
 'Votes: 312,442',
 'Votes: 433,293',
 'Votes: 522,261',
 'Votes: 148,401',
 'Votes: 144,540',
 'Votes: 398,625',
 'Votes: 221,742',
 'Votes: 409,724',
 'Votes: 425,334',
 'Votes: 963,128',
 'Votes: 668,551',
 'Votes: 400,304',
 'Votes: 377,808',
 'Votes: 133,219',
 'Votes: 122,794',
 'Votes: 171,202',
 'Votes: 152,701',
 'Votes: 227,557',
 'Votes: 484,482',
 'Votes: 210,808',
 'Votes: 415,707',
 'Votes: 484,440',
 'Votes: 62,008',
 'Votes: 181,725',
 'Votes: 497,201',
 'Votes: 362,378',
 'Votes: 75,086',
 'Votes: 266,067',
 'Votes: 233,499',
 'Votes: 218,728',
 'Votes: 214,951',
 'Votes: 229,557',
 'Votes: 715,836',
 'Votes: 128,180',
 'Votes: 330,908',
 'Votes: 242,233',
 'Votes: 541,298',
 'Votes: 508,686',
 'Votes: 452,663',
 'Votes: 60,601',
 'Votes: 109,502',
 'Votes: 337,082',
 'Votes: 73,006',
 'Votes: 103,561',
 'Votes: 220,121',
 'Votes: 91,755',
 'Votes: 90,876',
 'Votes: 48,763',
 'Votes: 146,786',
 'Votes: 362,721',
 'Votes: 300,100',
 'Votes: 105,884',
 'Votes: 226,507',
 'Votes: 553,510',
 'Votes: 102,992',
 'Votes: 126,984',
 'Votes: 433,050',
 'Votes: 106,153',
 'Votes: 224,922',
 'Votes: 85,053',
 'Votes: 21,588',
 'Votes: 139,136',
 'Votes: 152,373',
 'Votes: 128,399',
 'Votes: 36,347',
 'Votes: 274,473',
 'Votes: 119,336',
 'Votes: 128,772',
 'Votes: 72,991',
 'Votes: 104,865',
 'Votes: 192,025',
 'Votes: 27,923',
 'Votes: 181,633',
 'Votes: 193,848',
 'Votes: 713,029',
 'Votes: 67,122',
 'Votes: 49,098',
 'Votes: 59,894',
 'Votes: 192,255',
 'Votes: 40,598',
 'Votes: 231,253']

In [162]:
Votes=pd.DataFrame(Vote1)

In [163]:
TV_Series=pd.concat([Names,Year_Span,Genres,Run_Time,Ratings,Votes],axis=1)
TV_Series.columns=['Name','Year_Span','Genre','Run_Time','Ratings','Votes']
TV_Series

,Name,Year_Span,Genre,Run_Time,Ratings,Votes
0,1. Game of Thrones,2011–2019,"Action, Adventure, Drama",57 min,9.2,"Votes: 2,009,458"
1,2. Stranger Things,2016–,"Drama, Fantasy, Horror",51 min,8.7,"Votes: 1,090,617"
2,3. The Walking Dead,2010–2022,"Drama, Horror, Thriller",44 min,8.2,"Votes: 955,155"
3,4. 13 Reasons Why,2017–2020,"Drama, Mystery, Thriller",60 min,7.5,"Votes: 285,549"
4,5. The 100,2014–2020,"Drama, Mystery, Sci-Fi",43 min,7.6,"Votes: 245,207"
...,...,...,...,...,...,...
95,96. Reign,2013–2017,Drama,42 min,7.4,"Votes: 49,098"
96,97. A Series of Unfortunate Events,2017–2019,"Adventure, Comedy, Drama",50 min,7.8,"Votes: 59,894"
97,98. Criminal Minds,2005–2020,"Crime, Drama, Mystery",42 min,8.1,"Votes: 192,255"
98,99. Scream: The TV Series,2015–2019,"Comedy, Crime, Drama",45 min,7.1,"Votes: 40,598"
99,100. The Haunting of Hill House,2018,"Drama, Horror, Mystery",572 min,8.6,"Votes: 231,253"

# Data Set

In [164]:
driver.get("https://archive.ics.uci.edu/ml/index.php")

In [165]:
Data_Set=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td/span/b/a")
Data_Set.click() #Clicking on all dataset button

In [166]:
Data=[]
Data_Tag=driver.find_elements_by_xpath("//p[@class='normal']")
for i in Data_Tag:
    Data.append(i.text)
Data

['Classification (466)\nRegression (151)\nClustering (121)\nOther (56)',
 'Categorical (38)\nNumerical (422)\nMixed (55)',
 'Multivariate (480)\nUnivariate (30)\nSequential (59)\nTime-Series (126)\nText (69)\nDomain-Theory (23)\nOther (21)',
 'Life Sciences (147)\nPhysical Sciences (57)\nCS / Engineering (234)\nSocial Sciences (41)\nBusiness (45)\nGame (12)\nOther (81)',
 'Less than 10 (166)\n10 to 100 (279)\nGreater than 100 (110)',
 'Less than 100 (38)\n100 to 1000 (210)\nGreater than 1000 (339)',
 'Matrix (439)\nNon-Matrix (183)',
 'Table View  List View',
 'Abalone',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '4177 ',
 '8 ',
 '1995 ',
 'Adult',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Annealing',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '798 ',
 '38 ',
 ' ',
 'Anonymous Microsoft Web Data',
 ' ',
 'Recommender-Systems ',
 'Categorical ',
 '37711 ',
 '294 ',
 '1998 ',
 'Arrhythmia',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '452 ',
 '279 ',
 '1998 ',
 'Artificial Characters',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '6000 ',
 '7 ',
 '1992 ',
 'Audiology (Original)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 ' ',
 '1987 ',
 'Audiology (Standardized)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 '69 ',
 '1992 ',
 'Auto MPG',
 'Multivariate ',
 'Regression ',
 'Categorical, Real ',
 '398 ',
 '8 ',
 '1993 ',
 'Automobile',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer, Real ',
 '205 ',
 '26 ',
 '1987 ',
 'Badges',
 'Univariate, Text ',
 'Classification ',
 ' ',
 '294 ',
 '1 ',
 '1994 ',
 'Balance Scale',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '625 ',
 '4 ',
 '1994 ',
 'Balloons',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '16 ',
 '4 ',
 ' ',
 'Breast Cancer',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '286 ',
 '9 ',
 '1988 ',
 'Breast Cancer Wisconsin (Original)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '699 ',
 '10 ',
 '1992 ',
 'Breast Cancer Wisconsin (Prognostic)',
 'Multivariate ',
 'Classification, Regression ',
 'Real ',
 '198 ',
 '34 ',
 '1995 ',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '569 ',
 '32 ',
 '1995 ',
 'Pittsburgh Bridges',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '108 ',
 '13 ',
 '1990 ',
 'Car Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '1728 ',
 '6 ',
 '1997 ',
 'Census Income',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Chess (King-Rook vs. King-Knight)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical, Integer ',
 ' ',
 '22 ',
 '1988 ',
 'Chess (King-Rook vs. King-Pawn)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '3196 ',
 '36 ',
 '1989 ',
 'Chess (King-Rook vs. King)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '28056 ',
 '6 ',
 '1994 ',
 'Chess (Domain Theories)',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Bach Chorales',
 'Univariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 '100 ',
 '6 ',
 ' ',
 'Connect-4',
 'Multivariate, Spatial ',
 'Classification ',
 'Categorical ',
 '67557 ',
 '42 ',
 '1995 ',
 'Credit Approval',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '15 ',
 ' ',
 'Japanese Credit Screening',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real, Integer ',
 '125 ',
 ' ',
 '1992 ',
 'Computer Hardware',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '209 ',
 '9 ',
 '1987 ',
 'Contraceptive Method Choice',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1473 ',
 '9 ',
 '1997 ',
 'Covertype',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '581012 ',
 '54 ',
 '1998 ',
 'Cylinder Bands',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '512 ',
 '39 ',
 '1995 ',
 'Dermatology',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '366 ',
 '33 ',
 '1998 ',
 'Diabetes',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 ' ',
 '20 ',
 ' ',
 'DGP2 - The Second Data Generation Program',
 'Data-Generator ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Document Understanding',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 'EBL Domain Theories',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Echocardiogram',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '132 ',
 '12 ',
 '1989 ',
 'Ecoli',
 'Multivariate ',
 'Classification ',
 'Real ',
 '336 ',
 '8 ',
 '1996 ',
 'Flags',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '194 ',
 '30 ',
 '1990 ',
 'Function Finding',
 ' ',
 'Function-Learning ',
 'Real ',
 '352 ',
 ' ',
 '1990 ',
 'Glass Identification',
 'Multivariate ',
 'Classification ',
 'Real ',
 '214 ',
 '10 ',
 '1987 ',
 "Haberman's Survival",
 'Multivariate ',
 'Classification ',
 'Integer ',
 '306 ',
 '3 ',
 '1999 ',
 'Hayes-Roth',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '160 ',
 '5 ',
 '1989 ',
 'Heart Disease',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '303 ',
 '75 ',
 '1988 ',
 'Hepatitis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '155 ',
 '19 ',
 '1988 ',
 'Horse Colic',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '368 ',
 '27 ',
 '1989 ',
 'ICU',
 'Multivariate, Time-Series ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Image Segmentation',
 'Multivariate ',
 'Classification ',
 'Real ',
 '2310 ',
 '19 ',
 '1990 ',
 'Internet Advertisements',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '3279 ',
 '1558 ',
 '1998 ',
 'Ionosphere',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '351 ',
 '34 ',
 '1989 ',
 'Iris',
 'Multivariate ',
 'Classification ',
 'Real ',
 '150 ',
 '4 ',
 '1988 ',
 'ISOLET',
 'Multivariate ',
 'Classification ',
 'Real ',
 '7797 ',
 '617 ',
 '1994 ',
 'Kinship',
 'Relational ',
 'Relational-Learning ',
 'Categorical ',
 '104 ',
 '12 ',
 '1990 ',
 'Labor Relations',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '57 ',
 '16 ',
 '1988 ',
 'LED Display Domain',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical ',
 ' ',
 '7 ',
 '1988 ',
 'Lenses',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '24 ',
 '4 ',
 '1990 ',
 'Letter Recognition',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '20000 ',
 '16 ',
 '1991 ',
 'Liver Disorders',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '345 ',
 '7 ',
 '1990 ',
 'Logic Theorist',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Lung Cancer',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '32 ',
 '56 ',
 '1992 ',
 'Lymphography',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '148 ',
 '18 ',
 '1988 ',
 'Mechanical Analysis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '209 ',
 '8 ',
 '1990 ',
 'Meta-data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '528 ',
 '22 ',
 '1996 ',
 'Mobile Robots',
 'Domain-Theory ',
 ' ',
 'Categorical, Integer, Real ',
 ' ',
 ' ',
 '1995 ',
 'Molecular Biology (Promoter Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '106 ',
 '58 ',
 '1990 ',
 'Molecular Biology (Protein Secondary Structure)',
 'Sequential ',
 'Classification ',
 'Categorical ',
 '128 ',
 ' ',
 ' ',
 'Molecular Biology (Splice-junction Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '3190 ',
 '61 ',
 '1992 ',
 "MONK's Problems",
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '432 ',
 '7 ',
 '1992 ',
 'Moral Reasoner',
 'Domain-Theory ',
 ' ',
 ' ',
 '202 ',
 ' ',
 '1994 ',
 'Multiple Features',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '2000 ',
 '649 ',
 ' ',
 'Mushroom',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '8124 ',
 '22 ',
 '1987 ',
 'Musk (Version 1)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '476 ',
 '168 ',
 '1994 ',
 'Musk (Version 2)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '6598 ',
 '168 ',
 '1994 ',
 'Nursery',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '12960 ',
 '8 ',
 '1997 ',
 'Othello Domain Theory',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1991 ',
 'Page Blocks Classification',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '5473 ',
 '10 ',
 '1995 ',
 'Optical Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '5620 ',
 '64 ',
 '1998 ',
 'Pen-Based Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '10992 ',
 '16 ',
 '1998 ',
 'Post-Operative Patient',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '90 ',
 '8 ',
 '1993 ',
 'Primary Tumor',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '339 ',
 '17 ',
 '1988 ',
 'Prodigy',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Qualitative Structure Activity Relationships',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Quadruped Mammals',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 ' ',
 '72 ',
 '1992 ',
 'Servo',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '167 ',
 '4 ',
 '1993 ',
 'Shuttle Landing Control',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '15 ',
 '6 ',
 '1988 ',
 'Solar Flare',
 'Multivariate ',
 'Regression ',
 'Categorical ',
 '1389 ',
 '10 ',
 '1989 ',
 'Soybean (Large)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '307 ',
 '35 ',
 '1988 ',
 'Soybean (Small)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '47 ',
 '35 ',
 '1987 ',
 'Challenger USA Space Shuttle O-Ring',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '23 ',
 '4 ',
 '1993 ',
 'Low Resolution Spectrometer',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '531 ',
 '102 ',
 '1988 ',
 'Spambase',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '4601 ',
 '57 ',
 '1999 ',
 'SPECT Heart',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '267 ',
 '22 ',
 '2001 ',
 'SPECTF Heart',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '267 ',
 '44 ',
 '2001 ',
 'Sponge',
 'Multivariate ',
 'Clustering ',
 'Categorical, Integer ',
 '76 ',
 '45 ',
 ' ',
 'Statlog Project',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1992 ',
 'Student Loan Relational',
 'Domain-Theory ',
 ' ',
 ' ',
 '1000 ',
 ' ',
 '1993 ',
 'Teaching Assistant Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '151 ',
 '5 ',
 '1997 ',
 'Tic-Tac-Toe Endgame',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '958 ',
 '9 ',
 '1991 ',
 'Thyroid Disease',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real ',
 '7200 ',
 '21 ',
 '1987 ',
 'Trains',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '10 ',
 '32 ',
 '1994 ',
 'University',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '285 ',
 '17 ',
 '1988 ',
 'Congressional Voting Records',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '435 ',
 '16 ',
 '1987 ',
 'Water Treatment Plant',
 'Multivariate ',
 'Clustering ',
 'Integer, Real ',
 '527 ',
 '38 ',
 '1993 ',
 'Waveform Database Generator (Version 1)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '21 ',
 '1988 ',
 'Waveform Database Generator (Version 2)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '40 ',
 '1988 ',
 'Wine',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '178 ',
 '13 ',
 '1991 ',
 'Yeast',
 'Multivariate ',
 'Classification ',
 'Real ',
 '1484 ',
 '8 ',
 '1996 ',
 'Zoo',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '101 ',
 '17 ',
 '1990 ',
 'Undocumented',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Twenty Newsgroups',
 'Text ',
 ' ',
 ' ',
 '20000 ',
 ' ',
 '1999 ',
 'Australian Sign Language signs',
 'Multivariate, Time-Series ',
 'Classification ',
 'Categorical, Real ',
 '6650 ',
 '15 ',
 '1999 ',
 'Australian Sign Language signs (High Quality)',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '2565 ',
 '22 ',
 '2002 ',
 'US Census Data (1990)',
 'Multivariate ',
 'Clustering ',
 'Categorical ',
 '2458285 ',
 '68 ',
 ' ',
 'Census-Income (KDD)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '299285 ',
 '40 ',
 '2000 ',
 'Coil 1999 Competition Data',
 'Multivariate ',
 ' ',
 'Categorical, Real ',
 '340 ',
 '17 ',
 '1999 ',
 'Corel Image Features',
 'Multivariate ',
 ' ',
 'Real ',
 '68040 ',
 '89 ',
 '1999 ',
 'E. Coli Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'EEG Database',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer, Real ',
 '122 ',
 '4 ',
 '1999 ',
 'El Nino',
 'Spatio-temporal ',
 ' ',
 'Integer, Real ',
 '178080 ',
 '12 ',
 '1999 ',
 'Entree Chicago Recommendation Data',
 'Transactional, Sequential ',
 'Recommender-Systems ',
 'Categorical ',
 '50672 ',
 ' ',
 '2000 ',
 'CMU Face Images',
 'Image ',
 'Classification ',
 'Integer ',
 '640 ',
 ' ',
 '1999 ',
 'Insurance Company Benchmark (COIL 2000)',
 'Multivariate ',
 'Regression, Description ',
 'Categorical, Integer ',
 '9000 ',
 '86 ',
 '2000 ',
 'Internet Usage Data',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '10104 ',
 '72 ',
 '1999 ',
 'IPUMS Census Database',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '256932 ',
 '61 ',
 '1999 ',
 'Japanese Vowels',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '640 ',
 '12 ',
 ' ',
 'KDD Cup 1998 Data',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '191779 ',
 '481 ',
 '1998 ',
 'KDD Cup 1999 Data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '4000000 ',
 '42 ',
 '1999 ',
 'M. Tuberculosis Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'Movie',
 'Multivariate, Relational ',
 ' ',
 ' ',
 '10000 ',
 ' ',
 '1999 ',
 'MSNBC.com Anonymous Web Data',
 'Sequential ',
 ' ',
 'Categorical ',
 '989818 ',
 ' ',
 ' ',
 'NSF Research Award Abstracts 1990-2003',
 'Text ',
 ' ',
 ' ',
 '129000 ',
 ' ',
 '2003 ',
 'Pioneer-1 Mobile Robot Data',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Real ',
 ' ',
 ' ',
 '1999 ',
 'Pseudo Periodic Synthetic Time Series',
 'Univariate, Time-Series ',
 ' ',
 ' ',
 '100000 ',
 ' ',
 '1999 ',
 'Reuters-21578 Text Categorization Collection',
 'Text ',
 'Classification ',
 'Categorical ',
 '21578 ',
 '5 ',
 '1997 ',
 'Robot Execution Failures',
 'Multivariate, Time-Series ',
 'Classification ',
 'Integer ',
 '463 ',
 '90 ',
 '1999 ',
 'Synthetic Control Chart Time Series',
 'Time-Series ',
 'Classification, Clustering ',
 'Real ',
 '600 ',
 ' ',
 '1999 ',
 'Syskill and Webert Web Page Ratings',
 'Multivariate, Text ',
 'Classification ',
 'Categorical ',
 '332 ',
 '5 ',
 '1998 ',
 'UNIX User Data',
 'Text, Sequential ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Volcanoes on Venus - JARtool experiment',
 'Image ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Statlog (Australian Credit Approval)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '14 ',
 ' ',
 'Statlog (German Credit Data)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1000 ',
 ...]

In [167]:
del Data[0:8] #Deleting the first 7 lines of Data for a proper slicing

In [168]:
Data #Checking

['Abalone',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '4177 ',
 '8 ',
 '1995 ',
 'Adult',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Annealing',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '798 ',
 '38 ',
 ' ',
 'Anonymous Microsoft Web Data',
 ' ',
 'Recommender-Systems ',
 'Categorical ',
 '37711 ',
 '294 ',
 '1998 ',
 'Arrhythmia',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '452 ',
 '279 ',
 '1998 ',
 'Artificial Characters',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '6000 ',
 '7 ',
 '1992 ',
 'Audiology (Original)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 ' ',
 '1987 ',
 'Audiology (Standardized)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 '69 ',
 '1992 ',
 'Auto MPG',
 'Multivariate ',
 'Regression ',
 'Categorical, Real ',
 '398 ',
 '8 ',
 '1993 ',
 'Automobile',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer, Real ',
 '205 ',
 '26 ',
 '1987 ',
 'Badges',
 'Univariate, Text ',
 'Classification ',
 ' ',
 '294 ',
 '1 ',
 '1994 ',
 'Balance Scale',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '625 ',
 '4 ',
 '1994 ',
 'Balloons',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '16 ',
 '4 ',
 ' ',
 'Breast Cancer',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '286 ',
 '9 ',
 '1988 ',
 'Breast Cancer Wisconsin (Original)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '699 ',
 '10 ',
 '1992 ',
 'Breast Cancer Wisconsin (Prognostic)',
 'Multivariate ',
 'Classification, Regression ',
 'Real ',
 '198 ',
 '34 ',
 '1995 ',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '569 ',
 '32 ',
 '1995 ',
 'Pittsburgh Bridges',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '108 ',
 '13 ',
 '1990 ',
 'Car Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '1728 ',
 '6 ',
 '1997 ',
 'Census Income',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Chess (King-Rook vs. King-Knight)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical, Integer ',
 ' ',
 '22 ',
 '1988 ',
 'Chess (King-Rook vs. King-Pawn)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '3196 ',
 '36 ',
 '1989 ',
 'Chess (King-Rook vs. King)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '28056 ',
 '6 ',
 '1994 ',
 'Chess (Domain Theories)',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Bach Chorales',
 'Univariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 '100 ',
 '6 ',
 ' ',
 'Connect-4',
 'Multivariate, Spatial ',
 'Classification ',
 'Categorical ',
 '67557 ',
 '42 ',
 '1995 ',
 'Credit Approval',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '15 ',
 ' ',
 'Japanese Credit Screening',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real, Integer ',
 '125 ',
 ' ',
 '1992 ',
 'Computer Hardware',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '209 ',
 '9 ',
 '1987 ',
 'Contraceptive Method Choice',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1473 ',
 '9 ',
 '1997 ',
 'Covertype',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '581012 ',
 '54 ',
 '1998 ',
 'Cylinder Bands',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '512 ',
 '39 ',
 '1995 ',
 'Dermatology',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '366 ',
 '33 ',
 '1998 ',
 'Diabetes',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 ' ',
 '20 ',
 ' ',
 'DGP2 - The Second Data Generation Program',
 'Data-Generator ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Document Understanding',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 'EBL Domain Theories',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Echocardiogram',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '132 ',
 '12 ',
 '1989 ',
 'Ecoli',
 'Multivariate ',
 'Classification ',
 'Real ',
 '336 ',
 '8 ',
 '1996 ',
 'Flags',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '194 ',
 '30 ',
 '1990 ',
 'Function Finding',
 ' ',
 'Function-Learning ',
 'Real ',
 '352 ',
 ' ',
 '1990 ',
 'Glass Identification',
 'Multivariate ',
 'Classification ',
 'Real ',
 '214 ',
 '10 ',
 '1987 ',
 "Haberman's Survival",
 'Multivariate ',
 'Classification ',
 'Integer ',
 '306 ',
 '3 ',
 '1999 ',
 'Hayes-Roth',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '160 ',
 '5 ',
 '1989 ',
 'Heart Disease',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '303 ',
 '75 ',
 '1988 ',
 'Hepatitis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '155 ',
 '19 ',
 '1988 ',
 'Horse Colic',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '368 ',
 '27 ',
 '1989 ',
 'ICU',
 'Multivariate, Time-Series ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Image Segmentation',
 'Multivariate ',
 'Classification ',
 'Real ',
 '2310 ',
 '19 ',
 '1990 ',
 'Internet Advertisements',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '3279 ',
 '1558 ',
 '1998 ',
 'Ionosphere',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '351 ',
 '34 ',
 '1989 ',
 'Iris',
 'Multivariate ',
 'Classification ',
 'Real ',
 '150 ',
 '4 ',
 '1988 ',
 'ISOLET',
 'Multivariate ',
 'Classification ',
 'Real ',
 '7797 ',
 '617 ',
 '1994 ',
 'Kinship',
 'Relational ',
 'Relational-Learning ',
 'Categorical ',
 '104 ',
 '12 ',
 '1990 ',
 'Labor Relations',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '57 ',
 '16 ',
 '1988 ',
 'LED Display Domain',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical ',
 ' ',
 '7 ',
 '1988 ',
 'Lenses',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '24 ',
 '4 ',
 '1990 ',
 'Letter Recognition',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '20000 ',
 '16 ',
 '1991 ',
 'Liver Disorders',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '345 ',
 '7 ',
 '1990 ',
 'Logic Theorist',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Lung Cancer',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '32 ',
 '56 ',
 '1992 ',
 'Lymphography',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '148 ',
 '18 ',
 '1988 ',
 'Mechanical Analysis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '209 ',
 '8 ',
 '1990 ',
 'Meta-data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '528 ',
 '22 ',
 '1996 ',
 'Mobile Robots',
 'Domain-Theory ',
 ' ',
 'Categorical, Integer, Real ',
 ' ',
 ' ',
 '1995 ',
 'Molecular Biology (Promoter Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '106 ',
 '58 ',
 '1990 ',
 'Molecular Biology (Protein Secondary Structure)',
 'Sequential ',
 'Classification ',
 'Categorical ',
 '128 ',
 ' ',
 ' ',
 'Molecular Biology (Splice-junction Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '3190 ',
 '61 ',
 '1992 ',
 "MONK's Problems",
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '432 ',
 '7 ',
 '1992 ',
 'Moral Reasoner',
 'Domain-Theory ',
 ' ',
 ' ',
 '202 ',
 ' ',
 '1994 ',
 'Multiple Features',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '2000 ',
 '649 ',
 ' ',
 'Mushroom',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '8124 ',
 '22 ',
 '1987 ',
 'Musk (Version 1)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '476 ',
 '168 ',
 '1994 ',
 'Musk (Version 2)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '6598 ',
 '168 ',
 '1994 ',
 'Nursery',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '12960 ',
 '8 ',
 '1997 ',
 'Othello Domain Theory',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1991 ',
 'Page Blocks Classification',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '5473 ',
 '10 ',
 '1995 ',
 'Optical Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '5620 ',
 '64 ',
 '1998 ',
 'Pen-Based Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '10992 ',
 '16 ',
 '1998 ',
 'Post-Operative Patient',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '90 ',
 '8 ',
 '1993 ',
 'Primary Tumor',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '339 ',
 '17 ',
 '1988 ',
 'Prodigy',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Qualitative Structure Activity Relationships',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Quadruped Mammals',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 ' ',
 '72 ',
 '1992 ',
 'Servo',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '167 ',
 '4 ',
 '1993 ',
 'Shuttle Landing Control',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '15 ',
 '6 ',
 '1988 ',
 'Solar Flare',
 'Multivariate ',
 'Regression ',
 'Categorical ',
 '1389 ',
 '10 ',
 '1989 ',
 'Soybean (Large)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '307 ',
 '35 ',
 '1988 ',
 'Soybean (Small)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '47 ',
 '35 ',
 '1987 ',
 'Challenger USA Space Shuttle O-Ring',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '23 ',
 '4 ',
 '1993 ',
 'Low Resolution Spectrometer',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '531 ',
 '102 ',
 '1988 ',
 'Spambase',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '4601 ',
 '57 ',
 '1999 ',
 'SPECT Heart',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '267 ',
 '22 ',
 '2001 ',
 'SPECTF Heart',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '267 ',
 '44 ',
 '2001 ',
 'Sponge',
 'Multivariate ',
 'Clustering ',
 'Categorical, Integer ',
 '76 ',
 '45 ',
 ' ',
 'Statlog Project',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1992 ',
 'Student Loan Relational',
 'Domain-Theory ',
 ' ',
 ' ',
 '1000 ',
 ' ',
 '1993 ',
 'Teaching Assistant Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '151 ',
 '5 ',
 '1997 ',
 'Tic-Tac-Toe Endgame',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '958 ',
 '9 ',
 '1991 ',
 'Thyroid Disease',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real ',
 '7200 ',
 '21 ',
 '1987 ',
 'Trains',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '10 ',
 '32 ',
 '1994 ',
 'University',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '285 ',
 '17 ',
 '1988 ',
 'Congressional Voting Records',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '435 ',
 '16 ',
 '1987 ',
 'Water Treatment Plant',
 'Multivariate ',
 'Clustering ',
 'Integer, Real ',
 '527 ',
 '38 ',
 '1993 ',
 'Waveform Database Generator (Version 1)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '21 ',
 '1988 ',
 'Waveform Database Generator (Version 2)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '40 ',
 '1988 ',
 'Wine',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '178 ',
 '13 ',
 '1991 ',
 'Yeast',
 'Multivariate ',
 'Classification ',
 'Real ',
 '1484 ',
 '8 ',
 '1996 ',
 'Zoo',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '101 ',
 '17 ',
 '1990 ',
 'Undocumented',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Twenty Newsgroups',
 'Text ',
 ' ',
 ' ',
 '20000 ',
 ' ',
 '1999 ',
 'Australian Sign Language signs',
 'Multivariate, Time-Series ',
 'Classification ',
 'Categorical, Real ',
 '6650 ',
 '15 ',
 '1999 ',
 'Australian Sign Language signs (High Quality)',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '2565 ',
 '22 ',
 '2002 ',
 'US Census Data (1990)',
 'Multivariate ',
 'Clustering ',
 'Categorical ',
 '2458285 ',
 '68 ',
 ' ',
 'Census-Income (KDD)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '299285 ',
 '40 ',
 '2000 ',
 'Coil 1999 Competition Data',
 'Multivariate ',
 ' ',
 'Categorical, Real ',
 '340 ',
 '17 ',
 '1999 ',
 'Corel Image Features',
 'Multivariate ',
 ' ',
 'Real ',
 '68040 ',
 '89 ',
 '1999 ',
 'E. Coli Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'EEG Database',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer, Real ',
 '122 ',
 '4 ',
 '1999 ',
 'El Nino',
 'Spatio-temporal ',
 ' ',
 'Integer, Real ',
 '178080 ',
 '12 ',
 '1999 ',
 'Entree Chicago Recommendation Data',
 'Transactional, Sequential ',
 'Recommender-Systems ',
 'Categorical ',
 '50672 ',
 ' ',
 '2000 ',
 'CMU Face Images',
 'Image ',
 'Classification ',
 'Integer ',
 '640 ',
 ' ',
 '1999 ',
 'Insurance Company Benchmark (COIL 2000)',
 'Multivariate ',
 'Regression, Description ',
 'Categorical, Integer ',
 '9000 ',
 '86 ',
 '2000 ',
 'Internet Usage Data',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '10104 ',
 '72 ',
 '1999 ',
 'IPUMS Census Database',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '256932 ',
 '61 ',
 '1999 ',
 'Japanese Vowels',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '640 ',
 '12 ',
 ' ',
 'KDD Cup 1998 Data',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '191779 ',
 '481 ',
 '1998 ',
 'KDD Cup 1999 Data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '4000000 ',
 '42 ',
 '1999 ',
 'M. Tuberculosis Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'Movie',
 'Multivariate, Relational ',
 ' ',
 ' ',
 '10000 ',
 ' ',
 '1999 ',
 'MSNBC.com Anonymous Web Data',
 'Sequential ',
 ' ',
 'Categorical ',
 '989818 ',
 ' ',
 ' ',
 'NSF Research Award Abstracts 1990-2003',
 'Text ',
 ' ',
 ' ',
 '129000 ',
 ' ',
 '2003 ',
 'Pioneer-1 Mobile Robot Data',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Real ',
 ' ',
 ' ',
 '1999 ',
 'Pseudo Periodic Synthetic Time Series',
 'Univariate, Time-Series ',
 ' ',
 ' ',
 '100000 ',
 ' ',
 '1999 ',
 'Reuters-21578 Text Categorization Collection',
 'Text ',
 'Classification ',
 'Categorical ',
 '21578 ',
 '5 ',
 '1997 ',
 'Robot Execution Failures',
 'Multivariate, Time-Series ',
 'Classification ',
 'Integer ',
 '463 ',
 '90 ',
 '1999 ',
 'Synthetic Control Chart Time Series',
 'Time-Series ',
 'Classification, Clustering ',
 'Real ',
 '600 ',
 ' ',
 '1999 ',
 'Syskill and Webert Web Page Ratings',
 'Multivariate, Text ',
 'Classification ',
 'Categorical ',
 '332 ',
 '5 ',
 '1998 ',
 'UNIX User Data',
 'Text, Sequential ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Volcanoes on Venus - JARtool experiment',
 'Image ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Statlog (Australian Credit Approval)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '14 ',
 ' ',
 'Statlog (German Credit Data)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1000 ',
 '20 ',
 '1994 ',
 'Statlog (Heart)',
 'Multivariate ',
 'Classification ',
 'Categorical, Real ',
 '270 ',
 '13 ',
 ...]

In [169]:
len (Data) #Checking the length of Data

4356

In [170]:
Name=Data[0:4356:7] 
Name #Checking the Data_Set name

['Abalone',
 'Adult',
 'Annealing',
 'Anonymous Microsoft Web Data',
 'Arrhythmia',
 'Artificial Characters',
 'Audiology (Original)',
 'Audiology (Standardized)',
 'Auto MPG',
 'Automobile',
 'Badges',
 'Balance Scale',
 'Balloons',
 'Breast Cancer',
 'Breast Cancer Wisconsin (Original)',
 'Breast Cancer Wisconsin (Prognostic)',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Pittsburgh Bridges',
 'Car Evaluation',
 'Census Income',
 'Chess (King-Rook vs. King-Knight)',
 'Chess (King-Rook vs. King-Pawn)',
 'Chess (King-Rook vs. King)',
 'Chess (Domain Theories)',
 'Bach Chorales',
 'Connect-4',
 'Credit Approval',
 'Japanese Credit Screening',
 'Computer Hardware',
 'Contraceptive Method Choice',
 'Covertype',
 'Cylinder Bands',
 'Dermatology',
 'Diabetes',
 'DGP2 - The Second Data Generation Program',
 'Document Understanding',
 'EBL Domain Theories',
 'Echocardiogram',
 'Ecoli',
 'Flags',
 'Function Finding',
 'Glass Identification',
 "Haberman's Survival",
 'Hayes-Roth',
 'Heart Disease',
 'Hepatitis',
 'Horse Colic',
 'ICU',
 'Image Segmentation',
 'Internet Advertisements',
 'Ionosphere',
 'Iris',
 'ISOLET',
 'Kinship',
 'Labor Relations',
 'LED Display Domain',
 'Lenses',
 'Letter Recognition',
 'Liver Disorders',
 'Logic Theorist',
 'Lung Cancer',
 'Lymphography',
 'Mechanical Analysis',
 'Meta-data',
 'Mobile Robots',
 'Molecular Biology (Promoter Gene Sequences)',
 'Molecular Biology (Protein Secondary Structure)',
 'Molecular Biology (Splice-junction Gene Sequences)',
 "MONK's Problems",
 'Moral Reasoner',
 'Multiple Features',
 'Mushroom',
 'Musk (Version 1)',
 'Musk (Version 2)',
 'Nursery',
 'Othello Domain Theory',
 'Page Blocks Classification',
 'Optical Recognition of Handwritten Digits',
 'Pen-Based Recognition of Handwritten Digits',
 'Post-Operative Patient',
 'Primary Tumor',
 'Prodigy',
 'Qualitative Structure Activity Relationships',
 'Quadruped Mammals',
 'Servo',
 'Shuttle Landing Control',
 'Solar Flare',
 'Soybean (Large)',
 'Soybean (Small)',
 'Challenger USA Space Shuttle O-Ring',
 'Low Resolution Spectrometer',
 'Spambase',
 'SPECT Heart',
 'SPECTF Heart',
 'Sponge',
 'Statlog Project',
 'Student Loan Relational',
 'Teaching Assistant Evaluation',
 'Tic-Tac-Toe Endgame',
 'Thyroid Disease',
 'Trains',
 'University',
 'Congressional Voting Records',
 'Water Treatment Plant',
 'Waveform Database Generator (Version 1)',
 'Waveform Database Generator (Version 2)',
 'Wine',
 'Yeast',
 'Zoo',
 'Undocumented',
 'Twenty Newsgroups',
 'Australian Sign Language signs',
 'Australian Sign Language signs (High Quality)',
 'US Census Data (1990)',
 'Census-Income (KDD)',
 'Coil 1999 Competition Data',
 'Corel Image Features',
 'E. Coli Genes',
 'EEG Database',
 'El Nino',
 'Entree Chicago Recommendation Data',
 'CMU Face Images',
 'Insurance Company Benchmark (COIL 2000)',
 'Internet Usage Data',
 'IPUMS Census Database',
 'Japanese Vowels',
 'KDD Cup 1998 Data',
 'KDD Cup 1999 Data',
 'M. Tuberculosis Genes',
 'Movie',
 'MSNBC.com Anonymous Web Data',
 'NSF Research Award Abstracts 1990-2003',
 'Pioneer-1 Mobile Robot Data',
 'Pseudo Periodic Synthetic Time Series',
 'Reuters-21578 Text Categorization Collection',
 'Robot Execution Failures',
 'Synthetic Control Chart Time Series',
 'Syskill and Webert Web Page Ratings',
 'UNIX User Data',
 'Volcanoes on Venus - JARtool experiment',
 'Statlog (Australian Credit Approval)',
 'Statlog (German Credit Data)',
 'Statlog (Heart)',
 'Statlog (Landsat Satellite)',
 'Statlog (Image Segmentation)',
 'Statlog (Shuttle)',
 'Statlog (Vehicle Silhouettes)',
 'Connectionist Bench (Nettalk Corpus)',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Connectionist Bench (Vowel Recognition - Deterding Data)',
 'Economic Sanctions',
 'Protein Data',
 'Cloud',
 'CalIt2 Building People Counts',
 'Dodgers Loop Sensor',
 'Poker Hand',
 'MAGIC Gamma Telescope',
 'UJI Pen Characters',
 'Mammographic Mass',
 'Forest Fires',
 'Reuters Transcribed Subset',
 'Bag of Words',
 'Concrete Compressive Strength',
 'Hill-Valley',
 'Arcene',
 'Dexter',
 'Dorothea',
 'Gisette',
 'Madelon',
 'Ozone Level Detection',
 'Abscisic Acid Signaling Network',
 'Parkinsons',
 'Character Trajectories',
 'Blood Transfusion Service Center',
 'UJI Pen Characters (Version 2)',
 'Semeion Handwritten Digit',
 'SECOM',
 'Plants',
 'Libras Movement',
 'Concrete Slump Test',
 'Communities and Crime',
 'Acute Inflammations',
 'Wine Quality',
 'URL Reputation',
 'p53 Mutants',
 'Parkinsons Telemonitoring',
 'Demospongiae',
 'Opinosis Opinion ⁄ Review',
 'Breast Tissue',
 'Cardiotocography',
 'Wall-Following Robot Navigation Data',
 'Spoken Arabic Digit',
 'Localization Data for Person Activity',
 'AutoUniv',
 'Steel Plates Faults',
 'MiniBooNE particle identification',
 'YearPredictionMSD',
 'PEMS-SF',
 'OpinRank Review Dataset',
 'Relative location of CT slices on axial axis',
 'Online Handwritten Assamese Characters Dataset',
 'PubChem Bioassay Data',
 'Record Linkage Comparison Patterns',
 'Communities and Crime Unnormalized',
 'Vertebral Column',
 'EMG Physical Action Data Set',
 'Vicon Physical Action Data Set',
 'Amazon Commerce reviews set',
 'Amazon Access Samples',
 'Reuter_50_50',
 'Farm Ads',
 'DBWorld e-mails',
 'KEGG Metabolic Relation Network (Directed)',
 'KEGG Metabolic Reaction Network (Undirected)',
 'Bank Marketing',
 'YouTube Comedy Slam Preference Data',
 'Gas Sensor Array Drift Dataset',
 'ILPD (Indian Liver Patient Dataset)',
 'OPPORTUNITY Activity Recognition',
 'Nomao',
 'SMS Spam Collection',
 'Skin Segmentation',
 'Planning Relax',
 'PAMAP2 Physical Activity Monitoring',
 'Restaurant & consumer data',
 'CNAE-9',
 'Individual household electric power consumption',
 'seeds',
 'Northix',
 'QtyT40I10D100K',
 'Legal Case Reports',
 'Human Activity Recognition Using Smartphones',
 'One-hundred plant species leaves data set',
 'Energy efficiency',
 'Yacht Hydrodynamics',
 'Fertility',
 'Daphnet Freezing of Gait',
 '3D Road Network (North Jutland, Denmark)',
 'ISTANBUL STOCK EXCHANGE',
 'Buzz in social media',
 'First-order theorem proving',
 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 'Gas sensor arrays in open sampling settings',
 'Climate Model Simulation Crashes',
 'MicroMass',
 'QSAR biodegradation',
 'BLOGGER',
 'Daily and Sports Activities',
 'User Knowledge Modeling',
 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 'NYSK',
 'Turkiye Student Evaluation',
 "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 'EEG Eye State',
 'Physicochemical Properties of Protein Tertiary Structure',
 'seismic-bumps',
 'banknote authentication',
 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 'YouTube Multiview Video Games Dataset',
 'Gas Sensor Array Drift Dataset at Different Concentrations',
 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'SkillCraft1 Master Table Dataset',
 'Weight Lifting Exercises monitored with Inertial Measurement Units',
 'SML2010',
 'Bike Sharing Dataset',
 'Predict keywords activities in a online social media',
 'Thoracic Surgery Data',
 'EMG dataset in Lower Limb',
 'SUSY',
 'HIGGS',
 'Qualitative_Bankruptcy',
 'LSVT Voice Rehabilitation',
 'Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Wilt',
 'User Identification From Walking Activity',
 'Activity Recognition from Single Chest-Mounted Accelerometer',
 'Leaf',
 'Dresses_Attribute_Sales',
 'Tamilnadu Electricity Board Hourly Readings',
 'Airfoil Self-Noise',
 'Wholesale customers',
 'Twitter Data set for Arabic Sentiment Analysis',
 'Combined Cycle Power Plant',
 'Urban Land Cover',
 'Diabetes 130-US hospitals for years 1999-2008',
 'Bach Choral Harmony',
 'StoneFlakes',
 'Tennis Major Tournament Match Statistics',
 'Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 'Gesture Phase Segmentation',
 'Perfume Data',
 'BlogFeedback',
 'REALDISP Activity Recognition Dataset',
 'Newspaper and magazine images segmentation dataset',
 'AAAI 2014 Accepted Papers',
 'Gas sensor array under flow modulation',
 'Gas sensor array exposed to turbulent gas mixtures',
 'UJIIndoorLoc',
 'Sentence Classification',
 'Dow Jones Index',
 'sEMG for Basic Hand movements',
 'AAAI 2013 Accepted Papers',
 'Geographical Original of Music',
 'Condition Based Maintenance of Naval Propulsion Plants',
 'Grammatical Facial Expressions',
 'NoisyOffice',
 'MHEALTH Dataset',
 'Student Performance',
 'ElectricityLoadDiagrams20112014',
 'Gas sensor array under dynamic gas mixtures',
 'microblogPCU',
 'Firm-Teacher_Clave-Direction_Classification',
 'Dataset for Sensorless Drive Diagnosis',
 'TV News Channel Commercial Detection Dataset',
 'Phishing Websites',
 'Greenhouse Gas Observing Network',
 'Diabetic Retinopathy Debrecen Data Set',
 'HIV-1 protease cleavage',
 'Sentiment Labelled Sentences',
 'Online News Popularity',
 'Forest type mapping',
 'wiki4HE',
 'Online Video Characteristics and Transcoding Time Dataset',
 'Chronic_Kidney_Disease',
 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 'Folio',
 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 'Cuff-Less Blood Pressure Estimation',
 'Smartphone-Based Recognition of Human Activities and Postural Transitions',
 'Mice Protein Expression',
 'UJIIndoorLoc-Mag',
 'Heterogeneity Activity Recognition',
 'Educational Process Mining (EPM): A Learning Analytics Data Set',
 'HEPMASS',
 'Indoor User Movement Prediction from RSS data',
 'Open University Learning Analytics dataset',
 'default of credit card clients',
 'Mesothelioma’s disease data set',
 'Online Retail',
 'SIFT10M',
 'GPS Trajectories',
 'Detect Malacious Executable(AntiVirus)',
 'Occupancy Detection',
 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 'News Aggregator',
 'Air Quality',
 'Twin gas sensor arrays',
 'Gas sensors for home activity monitoring',
 'Facebook Comment Volume Dataset',
 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 'Polish companies bankruptcy data',
 'Activity Recognition system based on Multisensor data fusion (AReM)',
 'Dota2 Games Results',
 'Facebook metrics',
 'UbiqLog (smartphone lifelogging)',
 'NIPS Conference Papers 1987-2015',
 'HTRU2',
 'Drug consumption (quantified)',
 'Appliances energy prediction',
 'Miskolc IIS Hybrid IPS',
 'KDC-4007 dataset Collection',
 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 'DrivFace',
 'Website Phishing',
 'YouTube Spam Collection',
 'Beijing PM2.5 Data',
 'Cargo 2000 Freight Tracking and Tracing',
 'Cervical cancer (Risk Factors)',
 'Quality Assessment of Digital Colposcopies',
 'KASANDR',
 'FMA: A Dataset For Music Analysis',
 'Air quality',
 'Epileptic Seizure Recognition',
 'Devanagari Handwritten Character Dataset',
 'Stock portfolio performance',
 'MoCap Hand Postures',
 'Early biomarkers of Parkinson�s disease based on natural connected speech',
 'Data for Software Engineering Teamwork Assessment in Education Setting',
 'PM2.5 Data of Five Chinese Cities',
 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 'Sales_Transactions_Dataset_Weekly',
 'Las Vegas Strip',
 'Eco-hotel',
 'MEU-Mobile KSD',
 'Crowdsourced Mapping',
 'gene expression cancer RNA-Seq',
 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 'chestnut – LARVIC',
 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 'Motion Capture Hand Postures',
 'Anuran Calls (MFCCs)',
 'TTC-3600: Benchmark dataset for Turkish text categorization',
 'Gastrointestinal Lesions in Regular Colonoscopy',
 'Daily Demand Forecasting Orders',
 'Paper Reviews',
 'extention of Z-Alizadeh sani dataset',
 'Z-Alizadeh Sani',
 'Dynamic Features of VirusShare Executables',
 'IDA2016Challenge',
 'DSRC Vehicle Communications',
 'Mturk User-Perceived Clusters over Images',
 'Character Font Images',
 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 'Autistic Spectrum Disorder Screening Data for Children',
 'Autistic Spectrum Disorder Screening Data for Adolescent',
 'APS Failure at Scania Trucks',
 'Wireless Indoor Localization',
 'HCC Survival',
 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 'University of Tehran Question Dataset 2016 (UTQD.2016)',
 'Autism Screening Adult',
 'Activity recognition with healthy older people using a batteryless wearable sensor',
 'Immunotherapy Dataset',
 'Cryotherapy Dataset',
 'OCT data & Color Fundus Images of Left & Right Eyes',
 'Discrete Tone Image Dataset',
 'News Popularity in Multiple Social Media Platforms',
 'Ultrasonic flowmeter diagnostics',
 'ICMLA 2014 Accepted Papers Data Set',
 'BLE RSSI Dataset for Indoor localization and Navigation',
 'Container Crane Controller Data Set',
 'Residential Building Data Set',
 'Health News in Twitter',
 'chipseq',
 'SGEMM GPU kernel performance',
 'Repeat Consumption Matrices',
 'detection_of_IoT_botnet_attacks_N_BaIoT',
 'Absenteeism at work',
 'SCADI',
 'Condition monitoring of hydraulic systems',
 'Carbon Nanotubes',
 'Optical Interconnection Network',
 'Sports articles for objectivity analysis',
 'Breast Cancer Coimbra',
 'GNFUV Unmanned Surface Vehicles Sensor Data',
 'Dishonest Internet users Dataset',
 'Victorian Era Authorship Attribution',
 'Simulated Falls and Daily Living Activities Data Set',
 'Multimodal Damage Identification for Humanitarian Computing',
 'EEG Steady-State Visual Evoked Potential Signals',
 'Roman Urdu Data Set',
 'Avila',
 'PANDOR',
 'Drug Review Dataset (Druglib.com)',
 'Drug Review Dataset (Drugs.com)',
 'Physical Unclonable Functions',
 'Superconductivty Data',
 'WESAD (Wearable Stress and Affect Detection)',
 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 'Student Academics Performance',
 'Online Shoppers Purchasing Intention Dataset',
 'PMU-UD',
 "Parkinson's Disease Classification",
 'Electrical Grid Stability Simulated Data',
 'Caesarian Section Classification Dataset',
 'BAUM-1',
 'BAUM-2',
 'Audit Data',
 'BuddyMove Data Set',
 'Real estate valuation data set',
 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 'Somerville Happiness Survey',
 '2.4 GHZ Indoor Channel Measurements',
 'EMG data for gestures',
 'Parking Birmingham',
 'Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 'Travel Reviews',
 'Tarvel Review Ratings',
 'Rice Leaf Diseases',
 'Gas sensor array temperature modulation',
 'Facebook Live Sellers in Thailand',
 'Parkinson Dataset with replicated acoustic features',
 'Metro Interstate Traffic Volume',
 'Query Analytics Workloads Dataset',
 'Wave Energy Converters',
 'PPG-DaLiA',
 'Alcohol QCM Sensor Dataset',
 'Divorce Predictors data set',
 'Incident management process enriched event log',
 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 'MEx',
 'Beijing Multi-Site Air-Quality Data',
 'Online Retail II',
 'Hepatitis C Virus (HCV) for Egyptian patients',
 'QSAR fish toxicity',
 'QSAR aquatic toxicity',
 'Human Activity Recognition from Continuous Ambient Sensor Data',
 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 'QSAR oral toxicity',
 'QSAR androgen receptor',
 'QSAR Bioconcentration classes dataset',
 'QSAR fish bioconcentration factor (BCF)',
 'A study of Asian Religious and Biblical Texts',
 'Real-time Election Results: Portugal 2019',
 'Bias correction of numerical prediction model temperature forecast',
 'Bar Crawl: Detecting Heavy Drinking',
 'Kitsune Network Attack Dataset',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'Speaker Accent Recognition',
 'Heart failure clinical records',
 'Deepfakes: Medical Image Tamper Detection',
 'selfBACK',
 'South German Credit',
 'Exasens',
 'Swarm Behaviour',
 'Crop mapping using fused optical-radar data set',
 'BitcoinHeistRansomwareAddressDataset',
 'Facebook Large Page-Page Network',
 'Amphibians',
 'Early stage diabetes risk prediction dataset.',
 'Turkish Spam V01',
 'Stock keeping units',
 'Demand Forecasting for a store',
 'Detect Malware Types',
 'Wave Energy Converters',
 'Youtube cookery channels viewers comments in Hinglish',
 'Pedestrian in Traffic Dataset',
 'Cervical Cancer Behavior Risk',
 'Sattriya_Dance_Single_Hand_Gestures Dataset',
 'Divorce Predictors data set',
 '3W dataset',
 'Malware static and dynamic features VxHeaven and Virus Total',
 'Internet Firewall Data',
 'User Profiling and Abusive Language Detection Dataset',
 'Estimation of obesity levels based on eating habits and physical condition',
 'Rice (Cammeo and Osmancik)',
 'Vehicle routing and scheduling problems',
 'Algerian Forest Fires Dataset',
 'Breath Metabolomics',
 'Horton General Hospital',
 'UrbanGB, urban road accidents coordinates labelled by the urban center',
 'Gas Turbine CO and NOx Emission Data Set',
 'Activity recognition using wearable physiological measurements',
 'clickstream data for online shopping',
 'CNNpred: CNN-based stock market prediction using a diverse set of variables',
 'Apartment for rent classified',
 ': Simulated Data set of Iraqi tourism places',
 'Nasarian CAD Dataset',
 'Monolithic Columns in Troad and Mysia Region',
 'Bar Crawl: Detecting Heavy Drinking',
 'Seoul Bike Sharing Demand',
 'Person Classification Gait Data',
 'Shill Bidding Dataset',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Bone marrow transplant: children',
 'Exasens',
 'COVID-19 Surveillance',
 'Refractive errors',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'CLINC150',
 'HCV data',
 'Taiwanese Bankruptcy Prediction',
 'South German Credit (UPDATE)',
 'IIWA14-R820-Gazebo-Dataset-10Trajectories',
 'Guitar Chords finger positions',
 'Russian Corpus of Biographical Texts',
 'Codon usage',
 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 'Myocardial infarction complications',
 'Hungarian Chickenpox Cases',
 'Simulated data for survival modelling',
 'Student Performance on an entrance examination',
 'Chemical Composition of Ceramic Samples',
 'Labeled Text Forum Threads Dataset',
 'Stock keeping units',
 'BLE RSSI dataset for Indoor localization',
 'Basketball dataset',
 'GitHub MUSAE',
 'Anticancer peptides',
 'Monolithic Columns in Troad and Mysia Region',
 'Gender by Name',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Shoulder Implant Manufacture Classification',
 'LastFM Asia Social Network',
 'Wheat kernels',
 'Productivity Prediction of Garment Employees',
 'Multi-view Brain Networks',
 'LastFM Asia Social Network',
 'Wisesight Sentiment Corpus',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Dry Bean Dataset',
 'in-vehicle coupon recommendation',
 'Gait Classification',
 'Wikipedia Math Essentials',
 'Wikipedia Math Essentials',
 'Synchronous Machine Data Set',
 'Average Localization Error (ALE) in sensor node localization process in WSNs',
 '9mers from cullpdb',
 'TamilSentiMix',
 'Accelerometer',
 'Synchronous Machine Data Set',
 'Pedal Me Bicycle Deliveries',
 'Turkish Headlines Dataset',
 'Secondary Mushroom Dataset',
 'Power consumption of Tetouan city',
 'Raisin Dataset',
 'Steel Industry Energy Consumption Dataset',
 'Gender Gap in Spanish WP',
 'Non verbal tourists data',
 'Roman Urdu Sentiment Analysis Dataset (RUSAD)',
 'TUANDROMD ( Tezpur University Android Malware Dataset)',
 'Higher Education Students Performance Evaluation Dataset',
 'Risk Factor prediction of Chronic Kidney Disease',
 'Lab Test',
 'Shoulder Implant Manufacture Classification',
 'Rocket League Skillshots Data Set',
 'Sepsis survival minimal clinical records',
 'Water Quality Prediction',
 'Traffic Flow Forecasting',
 'sentiment analysis in Saudi Arabia about distance education during Covid-19',
 'Kain Tradisional Sambas',

In [171]:
del Name[-1] #deleting the last element as its not a part of the data set

In [173]:
len(Name) #Checking the length

622

In [174]:
Data_set=pd.DataFrame(Name)

In [175]:
DataType=Data[1:4356:7] 
DataType #Slicing data type

['Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Univariate, Time-Series ',
 'Multivariate, Spatial ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Data-Generator ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Sequential, Domain-Theory ',
 'Sequential ',
 'Sequential, Domain-Theory ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Domain-Theory ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Time-Series ',
 'Spatio-temporal ',
 'Transactional, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Relational ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 'Univariate, Time-Series ',
 'Text ',
 'Multivariate, Time-Series ',
 'Time-Series ',
 'Multivariate, Text ',
 'Text, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Domain-Theory ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate, Text, Domain-Theory ',
 'Time-Series, Domain-Theory ',
 'Multivariate, Text, Domain-Theory ',
 'Text ',
 'Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate, Text, Domain-Theory ',
 'Univariate ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate, Text ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Sequential, Text ',
 'Multivariate, Univariate, Time-Series ',
 'Time-Series, Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Univariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Univariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series, Domain-Theory ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 ' ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Sequential, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 ' ',
 'Sequential ',
 'Univariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Text ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Univariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Sequential ',
 'Text ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Univariate ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate, Time-Series ',
 'Univariate ',
 ' In Collaboration With:']

In [176]:
del DataType[-1] #deleting the last element as its not a part of the data set

In [177]:
len(DataType)

622

In [178]:
Data_Type=pd.DataFrame(DataType)

In [179]:
Task=Data[2:4356:7] 
Task #Slicing default task

['Classification ',
 'Classification ',
 'Classification ',
 'Recommender-Systems ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Function-Learning ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Relational-Learning ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Recommender-Systems ',
 'Classification ',
 'Regression, Description ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Regression, Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering, Causa ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Regression ',
 ' ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Clustering ',
 'Classification, Regression ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Clustering ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Recommendation ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Regression, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Clustering ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ']

In [180]:
len(Task)

622

In [181]:
Default_Task=pd.DataFrame(Task)

In [182]:
Type=Data[3:4356:7] 
Type #Slicing attribute types

['Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical, Integer, Real ',
 ' ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Real, Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer, Real ',
 ' ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Real ',
 ' ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical ',
 ' ',
 'Categorical, Real ',
 ' ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Categorical ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Categorical ',
 'Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Categorical ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Integer ',
 'Integer ',
 'Integer ',
 ' ',
 'Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 ' ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ']

In [183]:
len(Type)

622

In [184]:
Attribute_Type=pd.DataFrame(Type)

In [185]:
Instances=Data[4:4356:7] 
Instances #Slicing number of instances

['4177 ',
 '48842 ',
 '798 ',
 '37711 ',
 '452 ',
 '6000 ',
 '226 ',
 '226 ',
 '398 ',
 '205 ',
 '294 ',
 '625 ',
 '16 ',
 '286 ',
 '699 ',
 '198 ',
 '569 ',
 '108 ',
 '1728 ',
 '48842 ',
 ' ',
 '3196 ',
 '28056 ',
 ' ',
 '100 ',
 '67557 ',
 '690 ',
 '125 ',
 '209 ',
 '1473 ',
 '581012 ',
 '512 ',
 '366 ',
 ' ',
 ' ',
 ' ',
 ' ',
 '132 ',
 '336 ',
 '194 ',
 '352 ',
 '214 ',
 '306 ',
 '160 ',
 '303 ',
 '155 ',
 '368 ',
 ' ',
 '2310 ',
 '3279 ',
 '351 ',
 '150 ',
 '7797 ',
 '104 ',
 '57 ',
 ' ',
 '24 ',
 '20000 ',
 '345 ',
 ' ',
 '32 ',
 '148 ',
 '209 ',
 '528 ',
 ' ',
 '106 ',
 '128 ',
 '3190 ',
 '432 ',
 '202 ',
 '2000 ',
 '8124 ',
 '476 ',
 '6598 ',
 '12960 ',
 ' ',
 '5473 ',
 '5620 ',
 '10992 ',
 '90 ',
 '339 ',
 ' ',
 ' ',
 ' ',
 '167 ',
 '15 ',
 '1389 ',
 '307 ',
 '47 ',
 '23 ',
 '531 ',
 '4601 ',
 '267 ',
 '267 ',
 '76 ',
 ' ',
 '1000 ',
 '151 ',
 '958 ',
 '7200 ',
 '10 ',
 '285 ',
 '435 ',
 '527 ',
 '5000 ',
 '5000 ',
 '178 ',
 '1484 ',
 '101 ',
 ' ',
 '20000 ',
 '6650 ',
 '2565 ',
 '2458285 ',
 '299285 ',
 '340 ',
 '68040 ',
 ' ',
 '122 ',
 '178080 ',
 '50672 ',
 '640 ',
 '9000 ',
 '10104 ',
 '256932 ',
 '640 ',
 '191779 ',
 '4000000 ',
 ' ',
 '10000 ',
 '989818 ',
 '129000 ',
 ' ',
 '100000 ',
 '21578 ',
 '463 ',
 '600 ',
 '332 ',
 ' ',
 ' ',
 '690 ',
 '1000 ',
 '270 ',
 '6435 ',
 '2310 ',
 '58000 ',
 '946 ',
 '20008 ',
 '208 ',
 '528 ',
 ' ',
 ' ',
 '1024 ',
 '10080 ',
 '50400 ',
 '1025010 ',
 '19020 ',
 '1364 ',
 '961 ',
 '517 ',
 '200 ',
 '8000000 ',
 '1030 ',
 '606 ',
 '900 ',
 '2600 ',
 '1950 ',
 '13500 ',
 '4400 ',
 '2536 ',
 '300 ',
 '197 ',
 '2858 ',
 '748 ',
 '11640 ',
 '1593 ',
 '1567 ',
 '22632 ',
 '360 ',
 '103 ',
 '1994 ',
 '120 ',
 '4898 ',
 '2396130 ',
 '16772 ',
 '5875 ',
 '503 ',
 '51 ',
 '106 ',
 '2126 ',
 '5456 ',
 '8800 ',
 '164860 ',
 ' ',
 '1941 ',
 '130065 ',
 '515345 ',
 '440 ',
 ' ',
 '53500 ',
 '8235 ',
 ' ',
 '5749132 ',
 '2215 ',
 '310 ',
 '10000 ',
 '3000 ',
 '1500 ',
 '30000 ',
 '2500 ',
 '4143 ',
 '64 ',
 '53414 ',
 '65554 ',
 '45211 ',
 '1138562 ',
 '13910 ',
 '583 ',
 '2551 ',
 '34465 ',
 '5574 ',
 '245057 ',
 '182 ',
 '3850505 ',
 '138 ',
 '1080 ',
 '2075259 ',
 '210 ',
 '115 ',
 '3960456 ',
 ' ',
 '10299 ',
 '1600 ',
 '768 ',
 '308 ',
 '100 ',
 '237 ',
 '434874 ',
 '536 ',
 '140000 ',
 '6118 ',
 '165632 ',
 '18000 ',
 '540 ',
 '931 ',
 '1055 ',
 '100 ',
 '9120 ',
 '403 ',
 '111740 ',
 '10421 ',
 '5820 ',
 '403 ',
 '14980 ',
 '45730 ',
 '2584 ',
 '1372 ',
 '306 ',
 '120000 ',
 '13910 ',
 '2747 ',
 '3395 ',
 '39242 ',
 '4137 ',
 '17389 ',
 '51 ',
 '470 ',
 '132 ',
 '5000000 ',
 '11000000 ',
 '250 ',
 '126 ',
 ' ',
 '4889 ',
 ' ',
 ' ',
 '340 ',
 '501 ',
 '45781 ',
 '1503 ',
 '440 ',
 '2000 ',
 '9568 ',
 '168 ',
 '100000 ',
 '5665 ',
 '79 ',
 '127 ',
 '1040 ',
 '9900 ',
 '560 ',
 '60021 ',
 '1419 ',
 '101 ',
 '399 ',
 '58 ',
 '180 ',
 '21048 ',
 ' ',
 '750 ',
 '3000 ',
 '150 ',
 '1059 ',
 '11934 ',
 '27965 ',
 '216 ',
 '120 ',
 '649 ',
 '370 ',
 '4178504 ',
 '221579 ',
 '10800 ',
 '58509 ',
 '129685 ',
 '2456 ',
 '2921 ',
 '1151 ',
 '6590 ',
 '3000 ',
 '39797 ',
 '326 ',
 '913 ',
 '168286 ',
 '400 ',
 '314080 ',
 '637 ',
 '1710671 ',
 '12000 ',
 '10929 ',
 '1080 ',
 '40000 ',
 '43930257 ',
 '230318 ',
 '10500000 ',
 '13197 ',
 ' ',
 '30000 ',
 '324 ',
 '541909 ',
 '11164866 ',
 '163 ',
 '373 ',
 '20560 ',
 '40 ',
 '422937 ',
 '9358 ',
 '640 ',
 '919438 ',
 '40949 ',
 '5744 ',
 '10503 ',
 '42240 ',
 '102944 ',
 '500 ',
 '9782222 ',
 '11463 ',
 '17898 ',
 '1885 ',
 '19735 ',
 '1540 ',
 '4007 ',
 '153540 ',
 '606 ',
 '1353 ',
 '1956 ',
 '43824 ',
 '3942 ',
 '858 ',
 '287 ',
 '17764280 ',
 '106574 ',
 '9358 ',
 '11500 ',
 '92000 ',
 '315 ',
 '78095 ',
 '130 ',
 '74 ',
 '52854 ',
 '77 ',
 '811 ',
 '504 ',
 '401 ',
 '2856 ',
 '10546 ',
 '801 ',
 '1540 ',
 '1451 ',
 '1075 ',
 '78095 ',
 '7195 ',
 '3600 ',
 '76 ',
 '60 ',
 '405 ',
 '303 ',
 '303 ',
 '107888 ',
 '76000 ',
 '10000 ',
 '180 ',
 '745000 ',
 '12234 ',
 '292 ',
 '104 ',
 '60000 ',
 '2000 ',
 '165 ',
 '217 ',
 '1175 ',
 '704 ',
 '75128 ',
 '90 ',
 '90 ',
 '50 ',
 '71 ',
 '93239 ',
 '540 ',
 '105 ',
 '6611 ',
 '15 ',
 '372 ',
 '58000 ',
 '4960 ',
 '241600 ',
 '130000 ',
 '7062606 ',
 '740 ',
 '70 ',
 '2205 ',
 '10721 ',
 '640 ',
 '1000 ',
 '116 ',
 '1672 ',
 '322 ',
 '93600 ',
 '3060 ',
 '5879 ',
 '9200 ',
 '20000 ',
 '20867 ',
 ' ',
 '4143 ',
 '215063 ',
 '6000000 ',
 '21263 ',
 '63000000 ',
 '10190 ',
 '300 ',
 '12330 ',
 '5180 ',
 '756 ',
 '10000 ',
 '80 ',
 '1184 ',
 '1047 ',
 '777 ',
 '249 ',
 '414 ',
 ' ',
 '143 ',
 '7840 ',
 '30000 ',
 '35717 ',
 '135 ',
 '980 ',
 '5456 ',
 '120 ',
 '4095000 ',
 '7051 ',
 '240 ',
 '48204 ',
 '260000 ',
 '288000 ',
 '8300000 ',
 '125 ',
 '170 ',
 '141712 ',
 '3916 ',
 '6262 ',
 '420768 ',
 '1067371 ',
 '1385 ',
 '908 ',
 '546 ',
 '13956534 ',
 '15630426 ',
 '8992 ',
 '1687 ',
 '779 ',
 '1056 ',
 '590 ',
 '21643 ',
 '7750 ',
 '14057567 ',
 '27170754 ',
 '597 ',
 '329 ',
 '299 ',
 '20000 ',
 '26136 ',
 '1000 ',
 '399 ',
 '24017 ',
 '325834 ',
 '2916697 ',
 '22470 ',
 '189 ',
 '520 ',
 '826 ',
 '2279 ',
 '28764 ',
 '7107 ',
 '288000 ',
 '9800 ',
 '4760 ',
 '72 ',
 '1450 ',
 '170 ',
 '1984 ',
 '2955 ',
 '65532 ',
 '65919 ',
 '2111 ',
 '3810 ',
 '18 ',
 '244 ',
 '104 ',
 '139 ',
 '360177 ',
 '36733 ',
 '4480 ',
 '165474 ',
 '1985 ',
 '10000 ',
 '232 ',
 '150 ',
 '11 ',
 '14057567 ',
 '8760 ',
 '48 ',
 '6321 ',
 '3150 ',
 '17256 ',
 '187 ',
 '399 ',
 '14 ',
 '467 ',
 '597 ',
 '23700 ',
 '615 ',
 '6819 ',
 '1000 ',
 ' ',
 '2633 ',
 '200 ',
 '13028 ',
 '800 ',
 '1700 ',
 '521 ',
 '120000 ',
 '666 ',
 '88 ',
 '200 ',
 '2279 ',
 '23570 ',
 '10000 ',
 '37700 ',
 '1850 ',
 '11 ',
 '147270 ',
 '3150 ',
 '17256 ',
 '597 ',
 '7624 ',
 '314 ',
 '1197 ',
 '70 ',
 '7624 ',
 '26737 ',
 '10000 ',
 '13611 ',
 '12684 ',
 '48 ',
 '731 ',
 '731 ',
 '557 ',
 '107 ',
 '158716 ',
 '15744 ',
 '153000 ',
 '557 ',
 '36 ',
 '4200 ',
 '61069 ',
 '52417 ',
 '900 ',
 '35040 ',
 '4746 ',
 '73 ',
 '11000 ',
 '4465 ',
 '145 ',
 '202 ',
 '221 ',
 '597 ',
 '298 ',
 '110341 ',
 '705 ',
 '2101 ',
 '1765 ',
 '150 ',
 '4000 ',
 '6272 ',
 '1996 ',
 '35040 ',
 '75840 ',
 '400 ',
 '1014 ',
 '10129 ',
 '4000 ']

In [186]:
len(Instances)

622

In [187]:
Number_Of_Instances=pd.DataFrame(Instances)

In [188]:
Attributes=Data[5:4356:7] 
Attributes #Slicing number of attributes

['8 ',
 '14 ',
 '38 ',
 '294 ',
 '279 ',
 '7 ',
 ' ',
 '69 ',
 '8 ',
 '26 ',
 '1 ',
 '4 ',
 '4 ',
 '9 ',
 '10 ',
 '34 ',
 '32 ',
 '13 ',
 '6 ',
 '14 ',
 '22 ',
 '36 ',
 '6 ',
 ' ',
 '6 ',
 '42 ',
 '15 ',
 ' ',
 '9 ',
 '9 ',
 '54 ',
 '39 ',
 '33 ',
 '20 ',
 ' ',
 ' ',
 ' ',
 '12 ',
 '8 ',
 '30 ',
 ' ',
 '10 ',
 '3 ',
 '5 ',
 '75 ',
 '19 ',
 '27 ',
 ' ',
 '19 ',
 '1558 ',
 '34 ',
 '4 ',
 '617 ',
 '12 ',
 '16 ',
 '7 ',
 '4 ',
 '16 ',
 '7 ',
 ' ',
 '56 ',
 '18 ',
 '8 ',
 '22 ',
 ' ',
 '58 ',
 ' ',
 '61 ',
 '7 ',
 ' ',
 '649 ',
 '22 ',
 '168 ',
 '168 ',
 '8 ',
 ' ',
 '10 ',
 '64 ',
 '16 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '72 ',
 '4 ',
 '6 ',
 '10 ',
 '35 ',
 '35 ',
 '4 ',
 '102 ',
 '57 ',
 '22 ',
 '44 ',
 '45 ',
 ' ',
 ' ',
 '5 ',
 '9 ',
 '21 ',
 '32 ',
 '17 ',
 '16 ',
 '38 ',
 '21 ',
 '40 ',
 '13 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '15 ',
 '22 ',
 '68 ',
 '40 ',
 '17 ',
 '89 ',
 ' ',
 '4 ',
 '12 ',
 ' ',
 ' ',
 '86 ',
 '72 ',
 '61 ',
 '12 ',
 '481 ',
 '42 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '5 ',
 '90 ',
 ' ',
 '5 ',
 ' ',
 ' ',
 '14 ',
 '20 ',
 '13 ',
 '36 ',
 '19 ',
 '9 ',
 '18 ',
 '4 ',
 '60 ',
 '10 ',
 ' ',
 ' ',
 '10 ',
 '4 ',
 '3 ',
 '11 ',
 '11 ',
 ' ',
 '6 ',
 '13 ',
 ' ',
 '100000 ',
 '9 ',
 '101 ',
 '10000 ',
 '20000 ',
 '100000 ',
 '5000 ',
 '500 ',
 '73 ',
 '43 ',
 '23 ',
 '3 ',
 '5 ',
 ' ',
 '256 ',
 '591 ',
 '70 ',
 '91 ',
 '10 ',
 '128 ',
 '6 ',
 '12 ',
 '3231961 ',
 '5409 ',
 '26 ',
 ' ',
 ' ',
 '10 ',
 '23 ',
 '24 ',
 '13 ',
 '8 ',
 ' ',
 '27 ',
 '50 ',
 '90 ',
 '138672 ',
 ' ',
 '386 ',
 ' ',
 ' ',
 '12 ',
 '147 ',
 '6 ',
 '8 ',
 '27 ',
 '10000 ',
 '20000 ',
 '10000 ',
 '54877 ',
 '4702 ',
 '24 ',
 '29 ',
 '17 ',
 '3 ',
 '128 ',
 '10 ',
 '242 ',
 '120 ',
 ' ',
 '4 ',
 '13 ',
 '52 ',
 '47 ',
 '857 ',
 '9 ',
 '7 ',
 '200 ',
 '4 ',
 ' ',
 '561 ',
 '64 ',
 '8 ',
 '7 ',
 '10 ',
 '9 ',
 '4 ',
 '8 ',
 '77 ',
 '51 ',
 '18 ',
 '1950000 ',
 '18 ',
 '1300 ',
 '41 ',
 '6 ',
 '5625 ',
 '5 ',
 ' ',
 '7 ',
 '33 ',
 '5 ',
 '15 ',
 '9 ',
 '19 ',
 '5 ',
 '5 ',
 '1000000 ',
 '129 ',
 ' ',
 '20 ',
 '152 ',
 '24 ',
 '16 ',
 '35 ',
 '17 ',
 '5 ',
 '18 ',
 '28 ',
 '7 ',
 '309 ',
 '3 ',
 '6 ',
 ' ',
 ' ',
 '16 ',
 '13 ',
 '5 ',
 '6 ',
 '8 ',
 '2 ',
 '4 ',
 '148 ',
 '55 ',
 '17 ',
 '8 ',
 '42 ',
 '26 ',
 '50 ',
 '2 ',
 '281 ',
 '120 ',
 ' ',
 '6 ',
 '120432 ',
 '150000 ',
 '529 ',
 ' ',
 '16 ',
 '2500 ',
 '5 ',
 '68 ',
 '16 ',
 '100 ',
 '216 ',
 '23 ',
 '33 ',
 '140256 ',
 '19 ',
 '20 ',
 '20 ',
 '49 ',
 '12 ',
 '30 ',
 '5232 ',
 '20 ',
 '1 ',
 ' ',
 '61 ',
 '27 ',
 '53 ',
 '11 ',
 '25 ',
 '0 ',
 '20 ',
 '9 ',
 '3 ',
 '561 ',
 '82 ',
 '13 ',
 '16 ',
 '13 ',
 '28 ',
 '4 ',
 ' ',
 '24 ',
 '34 ',
 '8 ',
 '128 ',
 '15 ',
 '513 ',
 '7 ',
 '7 ',
 '5 ',
 '15 ',
 '480000 ',
 '11 ',
 '54 ',
 '561 ',
 '64 ',
 '6 ',
 '116 ',
 '19 ',
 ' ',
 '5812 ',
 '9 ',
 '32 ',
 '29 ',
 '67 ',
 ' ',
 '25 ',
 '6400 ',
 '10 ',
 '5 ',
 '13 ',
 '98 ',
 '36 ',
 '69 ',
 '2158859 ',
 '518 ',
 '15 ',
 '179 ',
 ' ',
 '12 ',
 '38 ',
 '65 ',
 '102 ',
 '86 ',
 '7 ',
 '53 ',
 '20 ',
 '1 ',
 '71 ',
 '29 ',
 '20531 ',
 '65 ',
 '3 ',
 '22 ',
 '38 ',
 '22 ',
 '4814 ',
 '698 ',
 '13 ',
 '10 ',
 '59 ',
 '56 ',
 '482 ',
 '171 ',
 '5 ',
 '500 ',
 '411 ',
 '8519 ',
 '21 ',
 '21 ',
 '171 ',
 '7 ',
 '49 ',
 '12 ',
 '3 ',
 '21 ',
 '9 ',
 '8 ',
 '7 ',
 '2 ',
 '11 ',
 '11 ',
 '173 ',
 '5 ',
 '15 ',
 '3 ',
 '105 ',
 '25000 ',
 ' ',
 '18 ',
 '21000 ',
 '115 ',
 '21 ',
 '206 ',
 '43680 ',
 '8 ',
 '10 ',
 '59 ',
 '10 ',
 '5 ',
 '5 ',
 '1000 ',
 '138 ',
 ' ',
 '16 ',
 '2 ',
 '10 ',
 ' ',
 '8 ',
 '6 ',
 '129 ',
 '81 ',
 '12 ',
 '6 ',
 '22 ',
 '18 ',
 '9 ',
 '754 ',
 '14 ',
 '5 ',
 ' ',
 ' ',
 '18 ',
 '7 ',
 '7 ',
 ' ',
 '7 ',
 '5 ',
 '6 ',
 '4 ',
 '18 ',
 '11 ',
 '25 ',
 ' ',
 '20 ',
 '12 ',
 '46 ',
 '9 ',
 '8 ',
 '49 ',
 '11 ',
 '8 ',
 '54 ',
 '36 ',
 '3916 ',
 '710 ',
 '18 ',
 '8 ',
 '29 ',
 '7 ',
 '9 ',
 '37 ',
 '6 ',
 '1024 ',
 '1024 ',
 '14 ',
 '7 ',
 '8265 ',
 '29 ',
 '25 ',
 '3 ',
 '115 ',
 '1 ',
 '12 ',
 '13 ',
 '200000 ',
 '6 ',
 '21 ',
 '4 ',
 '2400 ',
 '175 ',
 '10 ',
 '4714 ',
 '23 ',
 '17 ',
 '2 ',
 '9 ',
 '8 ',
 '280 ',
 '49 ',
 '3 ',
 '14 ',
 '19 ',
 ' ',
 '54 ',
 '8 ',
 '1087 ',
 '12 ',
 '3 ',
 '17 ',
 '8 ',
 '9 ',
 '12 ',
 '1656 ',
 '6 ',
 '2 ',
 '11 ',
 '533 ',
 '14 ',
 '84 ',
 '22 ',
 '16 ',
 '52 ',
 '19 ',
 '3 ',
 '14 ',
 '321 ',
 '13 ',
 '13 ',
 '55 ',
 '39 ',
 '4 ',
 '7 ',
 '79 ',
 '1 ',
 ' ',
 '14 ',
 '96 ',
 '21 ',
 ' ',
 '5 ',
 '2 ',
 '69 ',
 '9 ',
 '124 ',
 '20 ',
 '25 ',
 '11 ',
 '19 ',
 '9 ',
 '9 ',
 '5 ',
 '7 ',
 '4006 ',
 '2 ',
 '19 ',
 '4 ',
 '13 ',
 '55 ',
 '1 ',
 '7842 ',
 '15 ',
 '15 ',
 '70 ',
 '7842 ',
 '4 ',
 '14 ',
 '17 ',
 '23 ',
 '321 ',
 '1068 ',
 '1068 ',
 '5 ',
 '6 ',
 '4 ',
 ' ',
 '5 ',
 '5 ',
 '15 ',
 '7 ',
 '21 ',
 '9 ',
 '8 ',
 '11 ',
 '21 ',
 '22 ',
 '2 ',
 '241 ',
 '33 ',
 '29 ',
 '7 ',
 '1 ',
 ' ',
 '4 ',
 '11 ',
 '47 ',
 '10 ',
 '3 ',
 '2 ',
 '632 ',
 '6826 ',
 '11 ',
 '525 ',
 '50 ',
 '7 ',
 '16 ',
 '2 ']

In [189]:
len(Attributes)

622

In [190]:
Number_Of_Attributes=pd.DataFrame(Attributes)

In [191]:
Year=Data[6:4356:7] 
Year #Slicing the year

['1995 ',
 '1996 ',
 ' ',
 '1998 ',
 '1998 ',
 '1992 ',
 '1987 ',
 '1992 ',
 '1993 ',
 '1987 ',
 '1994 ',
 '1994 ',
 ' ',
 '1988 ',
 '1992 ',
 '1995 ',
 '1995 ',
 '1990 ',
 '1997 ',
 '1996 ',
 '1988 ',
 '1989 ',
 '1994 ',
 ' ',
 ' ',
 '1995 ',
 ' ',
 '1992 ',
 '1987 ',
 '1997 ',
 '1998 ',
 '1995 ',
 '1998 ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1989 ',
 '1996 ',
 '1990 ',
 '1990 ',
 '1987 ',
 '1999 ',
 '1989 ',
 '1988 ',
 '1988 ',
 '1989 ',
 ' ',
 '1990 ',
 '1998 ',
 '1989 ',
 '1988 ',
 '1994 ',
 '1990 ',
 '1988 ',
 '1988 ',
 '1990 ',
 '1991 ',
 '1990 ',
 ' ',
 '1992 ',
 '1988 ',
 '1990 ',
 '1996 ',
 '1995 ',
 '1990 ',
 ' ',
 '1992 ',
 '1992 ',
 '1994 ',
 ' ',
 '1987 ',
 '1994 ',
 '1994 ',
 '1997 ',
 '1991 ',
 '1995 ',
 '1998 ',
 '1998 ',
 '1993 ',
 '1988 ',
 ' ',
 ' ',
 '1992 ',
 '1993 ',
 '1988 ',
 '1989 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1999 ',
 '2001 ',
 '2001 ',
 ' ',
 '1992 ',
 '1993 ',
 '1997 ',
 '1991 ',
 '1987 ',
 '1994 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1988 ',
 '1991 ',
 '1996 ',
 '1990 ',
 ' ',
 '1999 ',
 '1999 ',
 '2002 ',
 ' ',
 '2000 ',
 '1999 ',
 '1999 ',
 '2001 ',
 '1999 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '1999 ',
 ' ',
 '1998 ',
 '1999 ',
 '2001 ',
 '1999 ',
 ' ',
 '2003 ',
 '1999 ',
 '1999 ',
 '1997 ',
 '1999 ',
 '1999 ',
 '1998 ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1993 ',
 '1990 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1989 ',
 '2006 ',
 '2006 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2010 ',
 '2009 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2021 ']

In [192]:
len(Year)

622

In [193]:
Years=pd.DataFrame(Year)

In [194]:
Machine_Learning_Repository=pd.concat([Data_set,Data_Type,Default_Task,Attribute_Type,Number_Of_Instances,Number_Of_Attributes,Years],axis=1)
Machine_Learning_Repository.columns=['Data_set','Data_Type','Default_Task','Attribute_Type','No._of_Instances','No._of_Attributes','Year']
Machine_Learning_Repository

,Data_set,Data_Type,Default_Task,Attribute_Type,No._of_Instances,No._of_Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

In [270]:
driver.close()